/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// QuoteTermsAPIService QuoteTermsAPI service
type QuoteTermsAPIService service

type ApiAddQuoteTermRequest struct {
	ctx         context.Context
	ApiService  *QuoteTermsAPIService
	quoteId     string
	requestBody *QuoteTermView
}

func (r ApiAddQuoteTermRequest) RequestBody(requestBody QuoteTermView) ApiAddQuoteTermRequest {
	r.requestBody = &requestBody
	return r
}

func (r ApiAddQuoteTermRequest) Execute() (*QuoteTermView, *http.Response, error) {
	return r.ApiService.AddQuoteTermExecute(r)
}

/*
AddQuoteTerm Method for AddQuoteTerm

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param quoteId
	@return ApiAddQuoteTermRequest
*/
func (a *QuoteTermsAPIService) AddQuoteTerm(ctx context.Context, quoteId string) ApiAddQuoteTermRequest {
	return ApiAddQuoteTermRequest{
		ApiService: a,
		ctx:        ctx,
		quoteId:    quoteId,
	}
}

// Execute executes the request
//
//	@return QuoteTermView
func (a *QuoteTermsAPIService) AddQuoteTermExecute(r ApiAddQuoteTermRequest) (*QuoteTermView, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *QuoteTermView
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteTermsAPIService.AddQuoteTerm")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/quotes/{quoteId}/quoteTerms"
	localVarPath = strings.Replace(localVarPath, "{"+"quoteId"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestBody == nil {
		return localVarReturnValue, nil, reportError("requestBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json; version = 1.0"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteQuoteTermRequest struct {
	ctx        context.Context
	ApiService *QuoteTermsAPIService
	quoteId    string
	id         string
}

func (r ApiDeleteQuoteTermRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteQuoteTermExecute(r)
}

/*
DeleteQuoteTerm Method for DeleteQuoteTerm

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param quoteId
	@param id
	@return ApiDeleteQuoteTermRequest
*/
func (a *QuoteTermsAPIService) DeleteQuoteTerm(ctx context.Context, quoteId string, id string) ApiDeleteQuoteTermRequest {
	return ApiDeleteQuoteTermRequest{
		ApiService: a,
		ctx:        ctx,
		quoteId:    quoteId,
		id:         id,
	}
}

// Execute executes the request
func (a *QuoteTermsAPIService) DeleteQuoteTermExecute(r ApiDeleteQuoteTermRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteTermsAPIService.DeleteQuoteTerm")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/quotes/{quoteId}/quoteTerms/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"quoteId"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetQuoteTermsRequest struct {
	ctx           context.Context
	ApiService    *QuoteTermsAPIService
	quoteId       string
	includeFields *string
	conditions    *string
	page          *int32
	pageSize      *int32
}

// Comma separated list of fields to return.
func (r ApiGetQuoteTermsRequest) IncludeFields(includeFields string) ApiGetQuoteTermsRequest {
	r.includeFields = &includeFields
	return r
}

// Conditional retrieve statements.
func (r ApiGetQuoteTermsRequest) Conditions(conditions string) ApiGetQuoteTermsRequest {
	r.conditions = &conditions
	return r
}

// Page of results to get. 1-index based.
func (r ApiGetQuoteTermsRequest) Page(page int32) ApiGetQuoteTermsRequest {
	r.page = &page
	return r
}

// Page size of results to get. Max size 1000, default 50.
func (r ApiGetQuoteTermsRequest) PageSize(pageSize int32) ApiGetQuoteTermsRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiGetQuoteTermsRequest) Execute() ([]QuoteTermView, *http.Response, error) {
	return r.ApiService.GetQuoteTermsExecute(r)
}

/*
GetQuoteTerms Method for GetQuoteTerms

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param quoteId
	@return ApiGetQuoteTermsRequest
*/
func (a *QuoteTermsAPIService) GetQuoteTerms(ctx context.Context, quoteId string) ApiGetQuoteTermsRequest {
	return ApiGetQuoteTermsRequest{
		ApiService: a,
		ctx:        ctx,
		quoteId:    quoteId,
	}
}

// Execute executes the request
//
//	@return []QuoteTermView
func (a *QuoteTermsAPIService) GetQuoteTermsExecute(r ApiGetQuoteTermsRequest) ([]QuoteTermView, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []QuoteTermView
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteTermsAPIService.GetQuoteTerms")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/quotes/{quoteId}/quoteTerms"
	localVarPath = strings.Replace(localVarPath, "{"+"quoteId"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.includeFields != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "includeFields", r.includeFields, "", "")
	}
	if r.conditions != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "conditions", r.conditions, "", "")
	}
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pageSize", r.pageSize, "", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateQuoteTermRequest struct {
	ctx        context.Context
	ApiService *QuoteTermsAPIService
	quoteId    string
	id         string
	patch      *JsonPatchDocumentQuoteTermView
}

func (r ApiUpdateQuoteTermRequest) Patch(patch JsonPatchDocumentQuoteTermView) ApiUpdateQuoteTermRequest {
	r.patch = &patch
	return r
}

func (r ApiUpdateQuoteTermRequest) Execute() (*QuoteTermView, *http.Response, error) {
	return r.ApiService.UpdateQuoteTermExecute(r)
}

/*
UpdateQuoteTerm Method for UpdateQuoteTerm

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param quoteId
	@param id
	@return ApiUpdateQuoteTermRequest
*/
func (a *QuoteTermsAPIService) UpdateQuoteTerm(ctx context.Context, quoteId string, id string) ApiUpdateQuoteTermRequest {
	return ApiUpdateQuoteTermRequest{
		ApiService: a,
		ctx:        ctx,
		quoteId:    quoteId,
		id:         id,
	}
}

// Execute executes the request
//
//	@return QuoteTermView
func (a *QuoteTermsAPIService) UpdateQuoteTermExecute(r ApiUpdateQuoteTermRequest) (*QuoteTermView, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *QuoteTermView
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteTermsAPIService.UpdateQuoteTerm")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/quotes/{quoteId}/quoteTerms/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"quoteId"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.patch == nil {
		return localVarReturnValue, nil, reportError("patch is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json; version = 1.0"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.patch
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
