/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// QuoteCustomersAPIService QuoteCustomersAPI service
type QuoteCustomersAPIService service

type ApiDeleteQuoteCustomerForQuoteCustomerIDRequest struct {
	ctx        context.Context
	ApiService *QuoteCustomersAPIService
	quoteId    string
	id         string
}

func (r ApiDeleteQuoteCustomerForQuoteCustomerIDRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteQuoteCustomerForQuoteCustomerIDExecute(r)
}

/*
DeleteQuoteCustomerForQuoteCustomerID Method for DeleteQuoteCustomerForQuoteCustomerID

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param quoteId
	@param id
	@return ApiDeleteQuoteCustomerForQuoteCustomerIDRequest
*/
func (a *QuoteCustomersAPIService) DeleteQuoteCustomerForQuoteCustomerID(ctx context.Context, quoteId string, id string) ApiDeleteQuoteCustomerForQuoteCustomerIDRequest {
	return ApiDeleteQuoteCustomerForQuoteCustomerIDRequest{
		ApiService: a,
		ctx:        ctx,
		quoteId:    quoteId,
		id:         id,
	}
}

// Execute executes the request
func (a *QuoteCustomersAPIService) DeleteQuoteCustomerForQuoteCustomerIDExecute(r ApiDeleteQuoteCustomerForQuoteCustomerIDRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteCustomersAPIService.DeleteQuoteCustomerForQuoteCustomerID")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/quotes/{quoteId}/customers/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"quoteId"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetQuoteCustomersForQuoteIDRequest struct {
	ctx        context.Context
	ApiService *QuoteCustomersAPIService
	quoteId    string
}

func (r ApiGetQuoteCustomersForQuoteIDRequest) Execute() ([]CustomerView, *http.Response, error) {
	return r.ApiService.GetQuoteCustomersForQuoteIDExecute(r)
}

/*
GetQuoteCustomersForQuoteID Method for GetQuoteCustomersForQuoteID

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param quoteId
	@return ApiGetQuoteCustomersForQuoteIDRequest
*/
func (a *QuoteCustomersAPIService) GetQuoteCustomersForQuoteID(ctx context.Context, quoteId string) ApiGetQuoteCustomersForQuoteIDRequest {
	return ApiGetQuoteCustomersForQuoteIDRequest{
		ApiService: a,
		ctx:        ctx,
		quoteId:    quoteId,
	}
}

// Execute executes the request
//
//	@return []CustomerView
func (a *QuoteCustomersAPIService) GetQuoteCustomersForQuoteIDExecute(r ApiGetQuoteCustomersForQuoteIDRequest) ([]CustomerView, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []CustomerView
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteCustomersAPIService.GetQuoteCustomersForQuoteID")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/quotes/{quoteId}/customers"
	localVarPath = strings.Replace(localVarPath, "{"+"quoteId"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPatchQuoteCustomerForQuoteCustomerIDRequest struct {
	ctx        context.Context
	ApiService *QuoteCustomersAPIService
	quoteId    string
	id         string
	patch      *JsonPatchDocumentCustomerView
}

func (r ApiPatchQuoteCustomerForQuoteCustomerIDRequest) Patch(patch JsonPatchDocumentCustomerView) ApiPatchQuoteCustomerForQuoteCustomerIDRequest {
	r.patch = &patch
	return r
}

func (r ApiPatchQuoteCustomerForQuoteCustomerIDRequest) Execute() (*CustomerView, *http.Response, error) {
	return r.ApiService.PatchQuoteCustomerForQuoteCustomerIDExecute(r)
}

/*
PatchQuoteCustomerForQuoteCustomerID Method for PatchQuoteCustomerForQuoteCustomerID

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param quoteId
	@param id
	@return ApiPatchQuoteCustomerForQuoteCustomerIDRequest
*/
func (a *QuoteCustomersAPIService) PatchQuoteCustomerForQuoteCustomerID(ctx context.Context, quoteId string, id string) ApiPatchQuoteCustomerForQuoteCustomerIDRequest {
	return ApiPatchQuoteCustomerForQuoteCustomerIDRequest{
		ApiService: a,
		ctx:        ctx,
		quoteId:    quoteId,
		id:         id,
	}
}

// Execute executes the request
//
//	@return CustomerView
func (a *QuoteCustomersAPIService) PatchQuoteCustomerForQuoteCustomerIDExecute(r ApiPatchQuoteCustomerForQuoteCustomerIDRequest) (*CustomerView, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CustomerView
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteCustomersAPIService.PatchQuoteCustomerForQuoteCustomerID")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/quotes/{quoteId}/customers/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"quoteId"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.patch == nil {
		return localVarReturnValue, nil, reportError("patch is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json; version = 1.0"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.patch
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPutQuoteCustomerForQuoteCustomerIDRequest struct {
	ctx         context.Context
	ApiService  *QuoteCustomersAPIService
	quoteId     string
	id          string
	requestBody *CustomerView
}

func (r ApiPutQuoteCustomerForQuoteCustomerIDRequest) RequestBody(requestBody CustomerView) ApiPutQuoteCustomerForQuoteCustomerIDRequest {
	r.requestBody = &requestBody
	return r
}

func (r ApiPutQuoteCustomerForQuoteCustomerIDRequest) Execute() (*CustomerView, *http.Response, error) {
	return r.ApiService.PutQuoteCustomerForQuoteCustomerIDExecute(r)
}

/*
PutQuoteCustomerForQuoteCustomerID Method for PutQuoteCustomerForQuoteCustomerID

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param quoteId
	@param id
	@return ApiPutQuoteCustomerForQuoteCustomerIDRequest
*/
func (a *QuoteCustomersAPIService) PutQuoteCustomerForQuoteCustomerID(ctx context.Context, quoteId string, id string) ApiPutQuoteCustomerForQuoteCustomerIDRequest {
	return ApiPutQuoteCustomerForQuoteCustomerIDRequest{
		ApiService: a,
		ctx:        ctx,
		quoteId:    quoteId,
		id:         id,
	}
}

// Execute executes the request
//
//	@return CustomerView
func (a *QuoteCustomersAPIService) PutQuoteCustomerForQuoteCustomerIDExecute(r ApiPutQuoteCustomerForQuoteCustomerIDRequest) (*CustomerView, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CustomerView
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteCustomersAPIService.PutQuoteCustomerForQuoteCustomerID")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/quotes/{quoteId}/customers/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"quoteId"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestBody == nil {
		return localVarReturnValue, nil, reportError("requestBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json; version = 1.0"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
