/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
	"time"
)

// checks if the CustomerView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerView{}

// CustomerView struct for CustomerView
type CustomerView struct {
	AccountName           *string `json:"accountName,omitempty"`
	AccountNumber         *string `json:"accountNumber,omitempty"`
	Address1              *string `json:"address1,omitempty"`
	Address2              *string `json:"address2,omitempty"`
	City                  *string `json:"city,omitempty"`
	CompanyId             *string `json:"companyId,omitempty"`
	Country               *string `json:"country,omitempty"`
	CustomCustomerString1 *string `json:"customCustomerString1,omitempty"`
	CustomCustomerString2 *string `json:"customCustomerString2,omitempty"`
	CustomCustomerString3 *string `json:"customCustomerString3,omitempty"`
	CustomerSource        *string `json:"customerSource,omitempty"`
	CustomerSourceId      *string `json:"customerSourceId,omitempty"`
	// This field is Read Only.
	CustomerType *string `json:"customerType,omitempty"`
	DayPhone     *string `json:"dayPhone,omitempty"`
	Description  *string `json:"description,omitempty"`
	EmailAddress *string `json:"emailAddress,omitempty"`
	FirstName    *string `json:"firstName,omitempty"`
	// This field is Read Only.
	Id            *string `json:"id,omitempty"`
	IntegrationId *string `json:"integrationId,omitempty"`
	JobTitle      *string `json:"jobTitle,omitempty"`
	LastName      *string `json:"lastName,omitempty"`
	LocationId    *string `json:"locationId,omitempty"`
	MobilePhone   *string `json:"mobilePhone,omitempty"`
	// This field is Read Only.
	ModifyDate             *time.Time     `json:"modifyDate,omitempty"`
	PostalCode             *string        `json:"postalCode,omitempty"`
	PriceLevel             *string        `json:"priceLevel,omitempty"`
	PriceLevelName         *string        `json:"priceLevelName,omitempty"`
	Quote                  *ReferenceLink `json:"quote,omitempty"`
	RelationshipSinceDate  *time.Time     `json:"relationshipSinceDate,omitempty"`
	State                  *string        `json:"state,omitempty"`
	TaxExternalReferenceId *string        `json:"taxExternalReferenceId,omitempty"`
	Title                  *string        `json:"title,omitempty"`
	UserId                 *string        `json:"userId,omitempty"`
	AdditionalProperties   map[string]interface{}
}

type _CustomerView CustomerView

// NewCustomerView instantiates a new CustomerView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerView() *CustomerView {
	this := CustomerView{}
	return &this
}

// NewCustomerViewWithDefaults instantiates a new CustomerView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerViewWithDefaults() *CustomerView {
	this := CustomerView{}
	return &this
}

// GetAccountName returns the AccountName field value if set, zero value otherwise.
func (o *CustomerView) GetAccountName() string {
	if o == nil || IsNil(o.AccountName) {
		var ret string
		return ret
	}
	return *o.AccountName
}

// GetAccountNameOk returns a tuple with the AccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetAccountNameOk() (*string, bool) {
	if o == nil || IsNil(o.AccountName) {
		return nil, false
	}
	return o.AccountName, true
}

// HasAccountName returns a boolean if a field has been set.
func (o *CustomerView) HasAccountName() bool {
	if o != nil && !IsNil(o.AccountName) {
		return true
	}

	return false
}

// SetAccountName gets a reference to the given string and assigns it to the AccountName field.
func (o *CustomerView) SetAccountName(v string) {
	o.AccountName = &v
}

// GetAccountNumber returns the AccountNumber field value if set, zero value otherwise.
func (o *CustomerView) GetAccountNumber() string {
	if o == nil || IsNil(o.AccountNumber) {
		var ret string
		return ret
	}
	return *o.AccountNumber
}

// GetAccountNumberOk returns a tuple with the AccountNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetAccountNumberOk() (*string, bool) {
	if o == nil || IsNil(o.AccountNumber) {
		return nil, false
	}
	return o.AccountNumber, true
}

// HasAccountNumber returns a boolean if a field has been set.
func (o *CustomerView) HasAccountNumber() bool {
	if o != nil && !IsNil(o.AccountNumber) {
		return true
	}

	return false
}

// SetAccountNumber gets a reference to the given string and assigns it to the AccountNumber field.
func (o *CustomerView) SetAccountNumber(v string) {
	o.AccountNumber = &v
}

// GetAddress1 returns the Address1 field value if set, zero value otherwise.
func (o *CustomerView) GetAddress1() string {
	if o == nil || IsNil(o.Address1) {
		var ret string
		return ret
	}
	return *o.Address1
}

// GetAddress1Ok returns a tuple with the Address1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetAddress1Ok() (*string, bool) {
	if o == nil || IsNil(o.Address1) {
		return nil, false
	}
	return o.Address1, true
}

// HasAddress1 returns a boolean if a field has been set.
func (o *CustomerView) HasAddress1() bool {
	if o != nil && !IsNil(o.Address1) {
		return true
	}

	return false
}

// SetAddress1 gets a reference to the given string and assigns it to the Address1 field.
func (o *CustomerView) SetAddress1(v string) {
	o.Address1 = &v
}

// GetAddress2 returns the Address2 field value if set, zero value otherwise.
func (o *CustomerView) GetAddress2() string {
	if o == nil || IsNil(o.Address2) {
		var ret string
		return ret
	}
	return *o.Address2
}

// GetAddress2Ok returns a tuple with the Address2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetAddress2Ok() (*string, bool) {
	if o == nil || IsNil(o.Address2) {
		return nil, false
	}
	return o.Address2, true
}

// HasAddress2 returns a boolean if a field has been set.
func (o *CustomerView) HasAddress2() bool {
	if o != nil && !IsNil(o.Address2) {
		return true
	}

	return false
}

// SetAddress2 gets a reference to the given string and assigns it to the Address2 field.
func (o *CustomerView) SetAddress2(v string) {
	o.Address2 = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *CustomerView) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *CustomerView) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *CustomerView) SetCity(v string) {
	o.City = &v
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *CustomerView) GetCompanyId() string {
	if o == nil || IsNil(o.CompanyId) {
		var ret string
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetCompanyIdOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyId) {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *CustomerView) HasCompanyId() bool {
	if o != nil && !IsNil(o.CompanyId) {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given string and assigns it to the CompanyId field.
func (o *CustomerView) SetCompanyId(v string) {
	o.CompanyId = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *CustomerView) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *CustomerView) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *CustomerView) SetCountry(v string) {
	o.Country = &v
}

// GetCustomCustomerString1 returns the CustomCustomerString1 field value if set, zero value otherwise.
func (o *CustomerView) GetCustomCustomerString1() string {
	if o == nil || IsNil(o.CustomCustomerString1) {
		var ret string
		return ret
	}
	return *o.CustomCustomerString1
}

// GetCustomCustomerString1Ok returns a tuple with the CustomCustomerString1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetCustomCustomerString1Ok() (*string, bool) {
	if o == nil || IsNil(o.CustomCustomerString1) {
		return nil, false
	}
	return o.CustomCustomerString1, true
}

// HasCustomCustomerString1 returns a boolean if a field has been set.
func (o *CustomerView) HasCustomCustomerString1() bool {
	if o != nil && !IsNil(o.CustomCustomerString1) {
		return true
	}

	return false
}

// SetCustomCustomerString1 gets a reference to the given string and assigns it to the CustomCustomerString1 field.
func (o *CustomerView) SetCustomCustomerString1(v string) {
	o.CustomCustomerString1 = &v
}

// GetCustomCustomerString2 returns the CustomCustomerString2 field value if set, zero value otherwise.
func (o *CustomerView) GetCustomCustomerString2() string {
	if o == nil || IsNil(o.CustomCustomerString2) {
		var ret string
		return ret
	}
	return *o.CustomCustomerString2
}

// GetCustomCustomerString2Ok returns a tuple with the CustomCustomerString2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetCustomCustomerString2Ok() (*string, bool) {
	if o == nil || IsNil(o.CustomCustomerString2) {
		return nil, false
	}
	return o.CustomCustomerString2, true
}

// HasCustomCustomerString2 returns a boolean if a field has been set.
func (o *CustomerView) HasCustomCustomerString2() bool {
	if o != nil && !IsNil(o.CustomCustomerString2) {
		return true
	}

	return false
}

// SetCustomCustomerString2 gets a reference to the given string and assigns it to the CustomCustomerString2 field.
func (o *CustomerView) SetCustomCustomerString2(v string) {
	o.CustomCustomerString2 = &v
}

// GetCustomCustomerString3 returns the CustomCustomerString3 field value if set, zero value otherwise.
func (o *CustomerView) GetCustomCustomerString3() string {
	if o == nil || IsNil(o.CustomCustomerString3) {
		var ret string
		return ret
	}
	return *o.CustomCustomerString3
}

// GetCustomCustomerString3Ok returns a tuple with the CustomCustomerString3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetCustomCustomerString3Ok() (*string, bool) {
	if o == nil || IsNil(o.CustomCustomerString3) {
		return nil, false
	}
	return o.CustomCustomerString3, true
}

// HasCustomCustomerString3 returns a boolean if a field has been set.
func (o *CustomerView) HasCustomCustomerString3() bool {
	if o != nil && !IsNil(o.CustomCustomerString3) {
		return true
	}

	return false
}

// SetCustomCustomerString3 gets a reference to the given string and assigns it to the CustomCustomerString3 field.
func (o *CustomerView) SetCustomCustomerString3(v string) {
	o.CustomCustomerString3 = &v
}

// GetCustomerSource returns the CustomerSource field value if set, zero value otherwise.
func (o *CustomerView) GetCustomerSource() string {
	if o == nil || IsNil(o.CustomerSource) {
		var ret string
		return ret
	}
	return *o.CustomerSource
}

// GetCustomerSourceOk returns a tuple with the CustomerSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetCustomerSourceOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerSource) {
		return nil, false
	}
	return o.CustomerSource, true
}

// HasCustomerSource returns a boolean if a field has been set.
func (o *CustomerView) HasCustomerSource() bool {
	if o != nil && !IsNil(o.CustomerSource) {
		return true
	}

	return false
}

// SetCustomerSource gets a reference to the given string and assigns it to the CustomerSource field.
func (o *CustomerView) SetCustomerSource(v string) {
	o.CustomerSource = &v
}

// GetCustomerSourceId returns the CustomerSourceId field value if set, zero value otherwise.
func (o *CustomerView) GetCustomerSourceId() string {
	if o == nil || IsNil(o.CustomerSourceId) {
		var ret string
		return ret
	}
	return *o.CustomerSourceId
}

// GetCustomerSourceIdOk returns a tuple with the CustomerSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetCustomerSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerSourceId) {
		return nil, false
	}
	return o.CustomerSourceId, true
}

// HasCustomerSourceId returns a boolean if a field has been set.
func (o *CustomerView) HasCustomerSourceId() bool {
	if o != nil && !IsNil(o.CustomerSourceId) {
		return true
	}

	return false
}

// SetCustomerSourceId gets a reference to the given string and assigns it to the CustomerSourceId field.
func (o *CustomerView) SetCustomerSourceId(v string) {
	o.CustomerSourceId = &v
}

// GetCustomerType returns the CustomerType field value if set, zero value otherwise.
func (o *CustomerView) GetCustomerType() string {
	if o == nil || IsNil(o.CustomerType) {
		var ret string
		return ret
	}
	return *o.CustomerType
}

// GetCustomerTypeOk returns a tuple with the CustomerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetCustomerTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerType) {
		return nil, false
	}
	return o.CustomerType, true
}

// HasCustomerType returns a boolean if a field has been set.
func (o *CustomerView) HasCustomerType() bool {
	if o != nil && !IsNil(o.CustomerType) {
		return true
	}

	return false
}

// SetCustomerType gets a reference to the given string and assigns it to the CustomerType field.
func (o *CustomerView) SetCustomerType(v string) {
	o.CustomerType = &v
}

// GetDayPhone returns the DayPhone field value if set, zero value otherwise.
func (o *CustomerView) GetDayPhone() string {
	if o == nil || IsNil(o.DayPhone) {
		var ret string
		return ret
	}
	return *o.DayPhone
}

// GetDayPhoneOk returns a tuple with the DayPhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetDayPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.DayPhone) {
		return nil, false
	}
	return o.DayPhone, true
}

// HasDayPhone returns a boolean if a field has been set.
func (o *CustomerView) HasDayPhone() bool {
	if o != nil && !IsNil(o.DayPhone) {
		return true
	}

	return false
}

// SetDayPhone gets a reference to the given string and assigns it to the DayPhone field.
func (o *CustomerView) SetDayPhone(v string) {
	o.DayPhone = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CustomerView) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CustomerView) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CustomerView) SetDescription(v string) {
	o.Description = &v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise.
func (o *CustomerView) GetEmailAddress() string {
	if o == nil || IsNil(o.EmailAddress) {
		var ret string
		return ret
	}
	return *o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetEmailAddressOk() (*string, bool) {
	if o == nil || IsNil(o.EmailAddress) {
		return nil, false
	}
	return o.EmailAddress, true
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *CustomerView) HasEmailAddress() bool {
	if o != nil && !IsNil(o.EmailAddress) {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given string and assigns it to the EmailAddress field.
func (o *CustomerView) SetEmailAddress(v string) {
	o.EmailAddress = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *CustomerView) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *CustomerView) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *CustomerView) SetFirstName(v string) {
	o.FirstName = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CustomerView) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CustomerView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CustomerView) SetId(v string) {
	o.Id = &v
}

// GetIntegrationId returns the IntegrationId field value if set, zero value otherwise.
func (o *CustomerView) GetIntegrationId() string {
	if o == nil || IsNil(o.IntegrationId) {
		var ret string
		return ret
	}
	return *o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetIntegrationIdOk() (*string, bool) {
	if o == nil || IsNil(o.IntegrationId) {
		return nil, false
	}
	return o.IntegrationId, true
}

// HasIntegrationId returns a boolean if a field has been set.
func (o *CustomerView) HasIntegrationId() bool {
	if o != nil && !IsNil(o.IntegrationId) {
		return true
	}

	return false
}

// SetIntegrationId gets a reference to the given string and assigns it to the IntegrationId field.
func (o *CustomerView) SetIntegrationId(v string) {
	o.IntegrationId = &v
}

// GetJobTitle returns the JobTitle field value if set, zero value otherwise.
func (o *CustomerView) GetJobTitle() string {
	if o == nil || IsNil(o.JobTitle) {
		var ret string
		return ret
	}
	return *o.JobTitle
}

// GetJobTitleOk returns a tuple with the JobTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetJobTitleOk() (*string, bool) {
	if o == nil || IsNil(o.JobTitle) {
		return nil, false
	}
	return o.JobTitle, true
}

// HasJobTitle returns a boolean if a field has been set.
func (o *CustomerView) HasJobTitle() bool {
	if o != nil && !IsNil(o.JobTitle) {
		return true
	}

	return false
}

// SetJobTitle gets a reference to the given string and assigns it to the JobTitle field.
func (o *CustomerView) SetJobTitle(v string) {
	o.JobTitle = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *CustomerView) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *CustomerView) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *CustomerView) SetLastName(v string) {
	o.LastName = &v
}

// GetLocationId returns the LocationId field value if set, zero value otherwise.
func (o *CustomerView) GetLocationId() string {
	if o == nil || IsNil(o.LocationId) {
		var ret string
		return ret
	}
	return *o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetLocationIdOk() (*string, bool) {
	if o == nil || IsNil(o.LocationId) {
		return nil, false
	}
	return o.LocationId, true
}

// HasLocationId returns a boolean if a field has been set.
func (o *CustomerView) HasLocationId() bool {
	if o != nil && !IsNil(o.LocationId) {
		return true
	}

	return false
}

// SetLocationId gets a reference to the given string and assigns it to the LocationId field.
func (o *CustomerView) SetLocationId(v string) {
	o.LocationId = &v
}

// GetMobilePhone returns the MobilePhone field value if set, zero value otherwise.
func (o *CustomerView) GetMobilePhone() string {
	if o == nil || IsNil(o.MobilePhone) {
		var ret string
		return ret
	}
	return *o.MobilePhone
}

// GetMobilePhoneOk returns a tuple with the MobilePhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetMobilePhoneOk() (*string, bool) {
	if o == nil || IsNil(o.MobilePhone) {
		return nil, false
	}
	return o.MobilePhone, true
}

// HasMobilePhone returns a boolean if a field has been set.
func (o *CustomerView) HasMobilePhone() bool {
	if o != nil && !IsNil(o.MobilePhone) {
		return true
	}

	return false
}

// SetMobilePhone gets a reference to the given string and assigns it to the MobilePhone field.
func (o *CustomerView) SetMobilePhone(v string) {
	o.MobilePhone = &v
}

// GetModifyDate returns the ModifyDate field value if set, zero value otherwise.
func (o *CustomerView) GetModifyDate() time.Time {
	if o == nil || IsNil(o.ModifyDate) {
		var ret time.Time
		return ret
	}
	return *o.ModifyDate
}

// GetModifyDateOk returns a tuple with the ModifyDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetModifyDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModifyDate) {
		return nil, false
	}
	return o.ModifyDate, true
}

// HasModifyDate returns a boolean if a field has been set.
func (o *CustomerView) HasModifyDate() bool {
	if o != nil && !IsNil(o.ModifyDate) {
		return true
	}

	return false
}

// SetModifyDate gets a reference to the given time.Time and assigns it to the ModifyDate field.
func (o *CustomerView) SetModifyDate(v time.Time) {
	o.ModifyDate = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *CustomerView) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode) {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *CustomerView) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *CustomerView) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetPriceLevel returns the PriceLevel field value if set, zero value otherwise.
func (o *CustomerView) GetPriceLevel() string {
	if o == nil || IsNil(o.PriceLevel) {
		var ret string
		return ret
	}
	return *o.PriceLevel
}

// GetPriceLevelOk returns a tuple with the PriceLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetPriceLevelOk() (*string, bool) {
	if o == nil || IsNil(o.PriceLevel) {
		return nil, false
	}
	return o.PriceLevel, true
}

// HasPriceLevel returns a boolean if a field has been set.
func (o *CustomerView) HasPriceLevel() bool {
	if o != nil && !IsNil(o.PriceLevel) {
		return true
	}

	return false
}

// SetPriceLevel gets a reference to the given string and assigns it to the PriceLevel field.
func (o *CustomerView) SetPriceLevel(v string) {
	o.PriceLevel = &v
}

// GetPriceLevelName returns the PriceLevelName field value if set, zero value otherwise.
func (o *CustomerView) GetPriceLevelName() string {
	if o == nil || IsNil(o.PriceLevelName) {
		var ret string
		return ret
	}
	return *o.PriceLevelName
}

// GetPriceLevelNameOk returns a tuple with the PriceLevelName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetPriceLevelNameOk() (*string, bool) {
	if o == nil || IsNil(o.PriceLevelName) {
		return nil, false
	}
	return o.PriceLevelName, true
}

// HasPriceLevelName returns a boolean if a field has been set.
func (o *CustomerView) HasPriceLevelName() bool {
	if o != nil && !IsNil(o.PriceLevelName) {
		return true
	}

	return false
}

// SetPriceLevelName gets a reference to the given string and assigns it to the PriceLevelName field.
func (o *CustomerView) SetPriceLevelName(v string) {
	o.PriceLevelName = &v
}

// GetQuote returns the Quote field value if set, zero value otherwise.
func (o *CustomerView) GetQuote() ReferenceLink {
	if o == nil || IsNil(o.Quote) {
		var ret ReferenceLink
		return ret
	}
	return *o.Quote
}

// GetQuoteOk returns a tuple with the Quote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetQuoteOk() (*ReferenceLink, bool) {
	if o == nil || IsNil(o.Quote) {
		return nil, false
	}
	return o.Quote, true
}

// HasQuote returns a boolean if a field has been set.
func (o *CustomerView) HasQuote() bool {
	if o != nil && !IsNil(o.Quote) {
		return true
	}

	return false
}

// SetQuote gets a reference to the given ReferenceLink and assigns it to the Quote field.
func (o *CustomerView) SetQuote(v ReferenceLink) {
	o.Quote = &v
}

// GetRelationshipSinceDate returns the RelationshipSinceDate field value if set, zero value otherwise.
func (o *CustomerView) GetRelationshipSinceDate() time.Time {
	if o == nil || IsNil(o.RelationshipSinceDate) {
		var ret time.Time
		return ret
	}
	return *o.RelationshipSinceDate
}

// GetRelationshipSinceDateOk returns a tuple with the RelationshipSinceDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetRelationshipSinceDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RelationshipSinceDate) {
		return nil, false
	}
	return o.RelationshipSinceDate, true
}

// HasRelationshipSinceDate returns a boolean if a field has been set.
func (o *CustomerView) HasRelationshipSinceDate() bool {
	if o != nil && !IsNil(o.RelationshipSinceDate) {
		return true
	}

	return false
}

// SetRelationshipSinceDate gets a reference to the given time.Time and assigns it to the RelationshipSinceDate field.
func (o *CustomerView) SetRelationshipSinceDate(v time.Time) {
	o.RelationshipSinceDate = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *CustomerView) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *CustomerView) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *CustomerView) SetState(v string) {
	o.State = &v
}

// GetTaxExternalReferenceId returns the TaxExternalReferenceId field value if set, zero value otherwise.
func (o *CustomerView) GetTaxExternalReferenceId() string {
	if o == nil || IsNil(o.TaxExternalReferenceId) {
		var ret string
		return ret
	}
	return *o.TaxExternalReferenceId
}

// GetTaxExternalReferenceIdOk returns a tuple with the TaxExternalReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetTaxExternalReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaxExternalReferenceId) {
		return nil, false
	}
	return o.TaxExternalReferenceId, true
}

// HasTaxExternalReferenceId returns a boolean if a field has been set.
func (o *CustomerView) HasTaxExternalReferenceId() bool {
	if o != nil && !IsNil(o.TaxExternalReferenceId) {
		return true
	}

	return false
}

// SetTaxExternalReferenceId gets a reference to the given string and assigns it to the TaxExternalReferenceId field.
func (o *CustomerView) SetTaxExternalReferenceId(v string) {
	o.TaxExternalReferenceId = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CustomerView) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CustomerView) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CustomerView) SetTitle(v string) {
	o.Title = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *CustomerView) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerView) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *CustomerView) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *CustomerView) SetUserId(v string) {
	o.UserId = &v
}

func (o CustomerView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountName) {
		toSerialize["accountName"] = o.AccountName
	}
	if !IsNil(o.AccountNumber) {
		toSerialize["accountNumber"] = o.AccountNumber
	}
	if !IsNil(o.Address1) {
		toSerialize["address1"] = o.Address1
	}
	if !IsNil(o.Address2) {
		toSerialize["address2"] = o.Address2
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.CompanyId) {
		toSerialize["companyId"] = o.CompanyId
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.CustomCustomerString1) {
		toSerialize["customCustomerString1"] = o.CustomCustomerString1
	}
	if !IsNil(o.CustomCustomerString2) {
		toSerialize["customCustomerString2"] = o.CustomCustomerString2
	}
	if !IsNil(o.CustomCustomerString3) {
		toSerialize["customCustomerString3"] = o.CustomCustomerString3
	}
	if !IsNil(o.CustomerSource) {
		toSerialize["customerSource"] = o.CustomerSource
	}
	if !IsNil(o.CustomerSourceId) {
		toSerialize["customerSourceId"] = o.CustomerSourceId
	}
	if !IsNil(o.CustomerType) {
		toSerialize["customerType"] = o.CustomerType
	}
	if !IsNil(o.DayPhone) {
		toSerialize["dayPhone"] = o.DayPhone
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.EmailAddress) {
		toSerialize["emailAddress"] = o.EmailAddress
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IntegrationId) {
		toSerialize["integrationId"] = o.IntegrationId
	}
	if !IsNil(o.JobTitle) {
		toSerialize["jobTitle"] = o.JobTitle
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.LocationId) {
		toSerialize["locationId"] = o.LocationId
	}
	if !IsNil(o.MobilePhone) {
		toSerialize["mobilePhone"] = o.MobilePhone
	}
	if !IsNil(o.ModifyDate) {
		toSerialize["modifyDate"] = o.ModifyDate
	}
	if !IsNil(o.PostalCode) {
		toSerialize["postalCode"] = o.PostalCode
	}
	if !IsNil(o.PriceLevel) {
		toSerialize["priceLevel"] = o.PriceLevel
	}
	if !IsNil(o.PriceLevelName) {
		toSerialize["priceLevelName"] = o.PriceLevelName
	}
	if !IsNil(o.Quote) {
		toSerialize["quote"] = o.Quote
	}
	if !IsNil(o.RelationshipSinceDate) {
		toSerialize["relationshipSinceDate"] = o.RelationshipSinceDate
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.TaxExternalReferenceId) {
		toSerialize["taxExternalReferenceId"] = o.TaxExternalReferenceId
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerView) UnmarshalJSON(data []byte) (err error) {
	varCustomerView := _CustomerView{}

	err = json.Unmarshal(data, &varCustomerView)

	if err != nil {
		return err
	}

	*o = CustomerView(varCustomerView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "accountName")
		delete(additionalProperties, "accountNumber")
		delete(additionalProperties, "address1")
		delete(additionalProperties, "address2")
		delete(additionalProperties, "city")
		delete(additionalProperties, "companyId")
		delete(additionalProperties, "country")
		delete(additionalProperties, "customCustomerString1")
		delete(additionalProperties, "customCustomerString2")
		delete(additionalProperties, "customCustomerString3")
		delete(additionalProperties, "customerSource")
		delete(additionalProperties, "customerSourceId")
		delete(additionalProperties, "customerType")
		delete(additionalProperties, "dayPhone")
		delete(additionalProperties, "description")
		delete(additionalProperties, "emailAddress")
		delete(additionalProperties, "firstName")
		delete(additionalProperties, "id")
		delete(additionalProperties, "integrationId")
		delete(additionalProperties, "jobTitle")
		delete(additionalProperties, "lastName")
		delete(additionalProperties, "locationId")
		delete(additionalProperties, "mobilePhone")
		delete(additionalProperties, "modifyDate")
		delete(additionalProperties, "postalCode")
		delete(additionalProperties, "priceLevel")
		delete(additionalProperties, "priceLevelName")
		delete(additionalProperties, "quote")
		delete(additionalProperties, "relationshipSinceDate")
		delete(additionalProperties, "state")
		delete(additionalProperties, "taxExternalReferenceId")
		delete(additionalProperties, "title")
		delete(additionalProperties, "userId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomerView struct {
	value *CustomerView
	isSet bool
}

func (v NullableCustomerView) Get() *CustomerView {
	return v.value
}

func (v *NullableCustomerView) Set(val *CustomerView) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerView) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerView(val *CustomerView) *NullableCustomerView {
	return &NullableCustomerView{value: val, isSet: true}
}

func (v NullableCustomerView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
