/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
)

// checks if the JsonPatchDocumentQuoteView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JsonPatchDocumentQuoteView{}

// JsonPatchDocumentQuoteView struct for JsonPatchDocumentQuoteView
type JsonPatchDocumentQuoteView struct {
	// This field is Read Only.
	Operations           []OperationQuoteView `json:"operations,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JsonPatchDocumentQuoteView JsonPatchDocumentQuoteView

// NewJsonPatchDocumentQuoteView instantiates a new JsonPatchDocumentQuoteView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJsonPatchDocumentQuoteView() *JsonPatchDocumentQuoteView {
	this := JsonPatchDocumentQuoteView{}
	return &this
}

// NewJsonPatchDocumentQuoteViewWithDefaults instantiates a new JsonPatchDocumentQuoteView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJsonPatchDocumentQuoteViewWithDefaults() *JsonPatchDocumentQuoteView {
	this := JsonPatchDocumentQuoteView{}
	return &this
}

// GetOperations returns the Operations field value if set, zero value otherwise.
func (o *JsonPatchDocumentQuoteView) GetOperations() []OperationQuoteView {
	if o == nil || IsNil(o.Operations) {
		var ret []OperationQuoteView
		return ret
	}
	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JsonPatchDocumentQuoteView) GetOperationsOk() ([]OperationQuoteView, bool) {
	if o == nil || IsNil(o.Operations) {
		return nil, false
	}
	return o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *JsonPatchDocumentQuoteView) HasOperations() bool {
	if o != nil && !IsNil(o.Operations) {
		return true
	}

	return false
}

// SetOperations gets a reference to the given []OperationQuoteView and assigns it to the Operations field.
func (o *JsonPatchDocumentQuoteView) SetOperations(v []OperationQuoteView) {
	o.Operations = v
}

func (o JsonPatchDocumentQuoteView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JsonPatchDocumentQuoteView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Operations) {
		toSerialize["operations"] = o.Operations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JsonPatchDocumentQuoteView) UnmarshalJSON(data []byte) (err error) {
	varJsonPatchDocumentQuoteView := _JsonPatchDocumentQuoteView{}

	err = json.Unmarshal(data, &varJsonPatchDocumentQuoteView)

	if err != nil {
		return err
	}

	*o = JsonPatchDocumentQuoteView(varJsonPatchDocumentQuoteView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "operations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJsonPatchDocumentQuoteView struct {
	value *JsonPatchDocumentQuoteView
	isSet bool
}

func (v NullableJsonPatchDocumentQuoteView) Get() *JsonPatchDocumentQuoteView {
	return v.value
}

func (v *NullableJsonPatchDocumentQuoteView) Set(val *JsonPatchDocumentQuoteView) {
	v.value = val
	v.isSet = true
}

func (v NullableJsonPatchDocumentQuoteView) IsSet() bool {
	return v.isSet
}

func (v *NullableJsonPatchDocumentQuoteView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJsonPatchDocumentQuoteView(val *JsonPatchDocumentQuoteView) *NullableJsonPatchDocumentQuoteView {
	return &NullableJsonPatchDocumentQuoteView{value: val, isSet: true}
}

func (v NullableJsonPatchDocumentQuoteView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJsonPatchDocumentQuoteView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
