/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
)

// checks if the JsonPatchDocumentQuoteTermView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JsonPatchDocumentQuoteTermView{}

// JsonPatchDocumentQuoteTermView struct for JsonPatchDocumentQuoteTermView
type JsonPatchDocumentQuoteTermView struct {
	// This field is Read Only.
	Operations           []OperationQuoteTermView `json:"operations,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JsonPatchDocumentQuoteTermView JsonPatchDocumentQuoteTermView

// NewJsonPatchDocumentQuoteTermView instantiates a new JsonPatchDocumentQuoteTermView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJsonPatchDocumentQuoteTermView() *JsonPatchDocumentQuoteTermView {
	this := JsonPatchDocumentQuoteTermView{}
	return &this
}

// NewJsonPatchDocumentQuoteTermViewWithDefaults instantiates a new JsonPatchDocumentQuoteTermView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJsonPatchDocumentQuoteTermViewWithDefaults() *JsonPatchDocumentQuoteTermView {
	this := JsonPatchDocumentQuoteTermView{}
	return &this
}

// GetOperations returns the Operations field value if set, zero value otherwise.
func (o *JsonPatchDocumentQuoteTermView) GetOperations() []OperationQuoteTermView {
	if o == nil || IsNil(o.Operations) {
		var ret []OperationQuoteTermView
		return ret
	}
	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JsonPatchDocumentQuoteTermView) GetOperationsOk() ([]OperationQuoteTermView, bool) {
	if o == nil || IsNil(o.Operations) {
		return nil, false
	}
	return o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *JsonPatchDocumentQuoteTermView) HasOperations() bool {
	if o != nil && !IsNil(o.Operations) {
		return true
	}

	return false
}

// SetOperations gets a reference to the given []OperationQuoteTermView and assigns it to the Operations field.
func (o *JsonPatchDocumentQuoteTermView) SetOperations(v []OperationQuoteTermView) {
	o.Operations = v
}

func (o JsonPatchDocumentQuoteTermView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JsonPatchDocumentQuoteTermView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Operations) {
		toSerialize["operations"] = o.Operations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JsonPatchDocumentQuoteTermView) UnmarshalJSON(data []byte) (err error) {
	varJsonPatchDocumentQuoteTermView := _JsonPatchDocumentQuoteTermView{}

	err = json.Unmarshal(data, &varJsonPatchDocumentQuoteTermView)

	if err != nil {
		return err
	}

	*o = JsonPatchDocumentQuoteTermView(varJsonPatchDocumentQuoteTermView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "operations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJsonPatchDocumentQuoteTermView struct {
	value *JsonPatchDocumentQuoteTermView
	isSet bool
}

func (v NullableJsonPatchDocumentQuoteTermView) Get() *JsonPatchDocumentQuoteTermView {
	return v.value
}

func (v *NullableJsonPatchDocumentQuoteTermView) Set(val *JsonPatchDocumentQuoteTermView) {
	v.value = val
	v.isSet = true
}

func (v NullableJsonPatchDocumentQuoteTermView) IsSet() bool {
	return v.isSet
}

func (v *NullableJsonPatchDocumentQuoteTermView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJsonPatchDocumentQuoteTermView(val *JsonPatchDocumentQuoteTermView) *NullableJsonPatchDocumentQuoteTermView {
	return &NullableJsonPatchDocumentQuoteTermView{value: val, isSet: true}
}

func (v NullableJsonPatchDocumentQuoteTermView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJsonPatchDocumentQuoteTermView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
