/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
)

// checks if the RecurringRevenueView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecurringRevenueView{}

// RecurringRevenueView struct for RecurringRevenueView
type RecurringRevenueView struct {
	// This field is Read Only.
	Id                   *string `json:"id,omitempty"`
	Description          *string `json:"description,omitempty"`
	PeriodType           *string `json:"periodType,omitempty"`
	Duration             *int32  `json:"duration,omitempty"`
	ExternalXref         *string `json:"externalXref,omitempty"`
	Cycle                *string `json:"cycle,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RecurringRevenueView RecurringRevenueView

// NewRecurringRevenueView instantiates a new RecurringRevenueView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecurringRevenueView() *RecurringRevenueView {
	this := RecurringRevenueView{}
	return &this
}

// NewRecurringRevenueViewWithDefaults instantiates a new RecurringRevenueView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecurringRevenueViewWithDefaults() *RecurringRevenueView {
	this := RecurringRevenueView{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RecurringRevenueView) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurringRevenueView) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RecurringRevenueView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RecurringRevenueView) SetId(v string) {
	o.Id = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RecurringRevenueView) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurringRevenueView) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RecurringRevenueView) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RecurringRevenueView) SetDescription(v string) {
	o.Description = &v
}

// GetPeriodType returns the PeriodType field value if set, zero value otherwise.
func (o *RecurringRevenueView) GetPeriodType() string {
	if o == nil || IsNil(o.PeriodType) {
		var ret string
		return ret
	}
	return *o.PeriodType
}

// GetPeriodTypeOk returns a tuple with the PeriodType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurringRevenueView) GetPeriodTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PeriodType) {
		return nil, false
	}
	return o.PeriodType, true
}

// HasPeriodType returns a boolean if a field has been set.
func (o *RecurringRevenueView) HasPeriodType() bool {
	if o != nil && !IsNil(o.PeriodType) {
		return true
	}

	return false
}

// SetPeriodType gets a reference to the given string and assigns it to the PeriodType field.
func (o *RecurringRevenueView) SetPeriodType(v string) {
	o.PeriodType = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *RecurringRevenueView) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurringRevenueView) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *RecurringRevenueView) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *RecurringRevenueView) SetDuration(v int32) {
	o.Duration = &v
}

// GetExternalXref returns the ExternalXref field value if set, zero value otherwise.
func (o *RecurringRevenueView) GetExternalXref() string {
	if o == nil || IsNil(o.ExternalXref) {
		var ret string
		return ret
	}
	return *o.ExternalXref
}

// GetExternalXrefOk returns a tuple with the ExternalXref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurringRevenueView) GetExternalXrefOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalXref) {
		return nil, false
	}
	return o.ExternalXref, true
}

// HasExternalXref returns a boolean if a field has been set.
func (o *RecurringRevenueView) HasExternalXref() bool {
	if o != nil && !IsNil(o.ExternalXref) {
		return true
	}

	return false
}

// SetExternalXref gets a reference to the given string and assigns it to the ExternalXref field.
func (o *RecurringRevenueView) SetExternalXref(v string) {
	o.ExternalXref = &v
}

// GetCycle returns the Cycle field value if set, zero value otherwise.
func (o *RecurringRevenueView) GetCycle() string {
	if o == nil || IsNil(o.Cycle) {
		var ret string
		return ret
	}
	return *o.Cycle
}

// GetCycleOk returns a tuple with the Cycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurringRevenueView) GetCycleOk() (*string, bool) {
	if o == nil || IsNil(o.Cycle) {
		return nil, false
	}
	return o.Cycle, true
}

// HasCycle returns a boolean if a field has been set.
func (o *RecurringRevenueView) HasCycle() bool {
	if o != nil && !IsNil(o.Cycle) {
		return true
	}

	return false
}

// SetCycle gets a reference to the given string and assigns it to the Cycle field.
func (o *RecurringRevenueView) SetCycle(v string) {
	o.Cycle = &v
}

func (o RecurringRevenueView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecurringRevenueView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.PeriodType) {
		toSerialize["periodType"] = o.PeriodType
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.ExternalXref) {
		toSerialize["externalXref"] = o.ExternalXref
	}
	if !IsNil(o.Cycle) {
		toSerialize["cycle"] = o.Cycle
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RecurringRevenueView) UnmarshalJSON(data []byte) (err error) {
	varRecurringRevenueView := _RecurringRevenueView{}

	err = json.Unmarshal(data, &varRecurringRevenueView)

	if err != nil {
		return err
	}

	*o = RecurringRevenueView(varRecurringRevenueView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "description")
		delete(additionalProperties, "periodType")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "externalXref")
		delete(additionalProperties, "cycle")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRecurringRevenueView struct {
	value *RecurringRevenueView
	isSet bool
}

func (v NullableRecurringRevenueView) Get() *RecurringRevenueView {
	return v.value
}

func (v *NullableRecurringRevenueView) Set(val *RecurringRevenueView) {
	v.value = val
	v.isSet = true
}

func (v NullableRecurringRevenueView) IsSet() bool {
	return v.isSet
}

func (v *NullableRecurringRevenueView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecurringRevenueView(val *RecurringRevenueView) *NullableRecurringRevenueView {
	return &NullableRecurringRevenueView{value: val, isSet: true}
}

func (v NullableRecurringRevenueView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecurringRevenueView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
