/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
	"time"
)

// checks if the QuoteTermView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteTermView{}

// QuoteTermView struct for QuoteTermView
type QuoteTermView struct {
	// This field is Read Only.
	Id *string `json:"id,omitempty"`
	// This field is Read Only.
	IdQuote         *string  `json:"idQuote,omitempty"`
	Periods         *float64 `json:"periods,omitempty"`
	InterestRate    *float64 `json:"interestRate,omitempty"`
	DownPayment     *float64 `json:"downPayment,omitempty"`
	DiscountAmount  *float64 `json:"discountAmount,omitempty"`
	DiscountPercent *float64 `json:"discountPercent,omitempty"`
	// This field is Read Only.
	TotalAmount *float64 `json:"totalAmount,omitempty"`
	// This field is Read Only.
	Principal *float64 `json:"principal,omitempty"`
	// This field is Read Only.
	PeriodPaymentAmount      *float64 `json:"periodPaymentAmount,omitempty"`
	PeriodInterval           *string  `json:"periodInterval,omitempty"`
	IsSelected               *bool    `json:"isSelected,omitempty"`
	RecurringDiscountAmount  *float64 `json:"recurringDiscountAmount,omitempty"`
	RecurringDiscountPercent *float64 `json:"recurringDiscountPercent,omitempty"`
	// This field is Read Only.
	RecurringTotalAmount *float64 `json:"recurringTotalAmount,omitempty"`
	FinancingGroup       *string  `json:"financingGroup,omitempty"`
	Name                 *string  `json:"name,omitempty"`
	Description          *string  `json:"description,omitempty"`
	// This field is Read Only.
	RecurringBeforeDiscount      *float64 `json:"recurringBeforeDiscount,omitempty"`
	TabGroup                     *string  `json:"tabGroup,omitempty"`
	GroupSort                    *float64 `json:"groupSort,omitempty"`
	NameSort                     *float64 `json:"nameSort,omitempty"`
	TabName                      *string  `json:"tabName,omitempty"`
	TotalAmountOverride          *float64 `json:"totalAmountOverride,omitempty"`
	RecurringTotalAmountOverride *float64 `json:"recurringTotalAmountOverride,omitempty"`
	IdRecurringRevenue           *string  `json:"idRecurringRevenue,omitempty"`
	RecurringPeriods             *float64 `json:"recurringPeriods,omitempty"`
	// This field is Read Only.
	RecurringTotalAggregated    *float64   `json:"recurringTotalAggregated,omitempty"`
	SubscriptionName            *string    `json:"subscriptionName,omitempty"`
	IsAutomaticallyBillable     *bool      `json:"isAutomaticallyBillable,omitempty"`
	OverrideStartDate           *time.Time `json:"overrideStartDate,omitempty"`
	StartDateMode               *string    `json:"startDateMode,omitempty"`
	AuthorizeNetIntervalUnit    *string    `json:"authorizeNetIntervalUnit,omitempty"`
	AuthorizeNetIntervalLength  *int32     `json:"authorizeNetIntervalLength,omitempty"`
	AuthorizeNetTotalOccurances *int32     `json:"authorizeNetTotalOccurances,omitempty"`
	IntervalToStart             *int32     `json:"intervalToStart,omitempty"`
	OppRecurringAsAdjustment    *bool      `json:"oppRecurringAsAdjustment,omitempty"`
	SpreadOneTime               *bool      `json:"spreadOneTime,omitempty"`
	IsPrinted                   *bool      `json:"isPrinted,omitempty"`
	// This field is Read Only.
	RecurringRevenueLabel  *string  `json:"recurringRevenueLabel,omitempty"`
	TabExcludeFilter       *string  `json:"tabExcludeFilter,omitempty"`
	TabIncludeFilter       *string  `json:"tabIncludeFilter,omitempty"`
	IsRoundedPayments      *bool    `json:"isRoundedPayments,omitempty"`
	ObeyStandardTabFilters *bool    `json:"obeyStandardTabFilters,omitempty"`
	LeasingName            *string  `json:"leasingName,omitempty"`
	LeasingRate            *float64 `json:"leasingRate,omitempty"`
	LeasingRateOverride    *float64 `json:"leasingRateOverride,omitempty"`
	IsLease                *bool    `json:"isLease,omitempty"`
	LeaseMonthlyAmount     *float64 `json:"leaseMonthlyAmount,omitempty"`
	LeaseDownPayment       *float64 `json:"leaseDownPayment,omitempty"`
	IdLeasingRates         *string  `json:"idLeasingRates,omitempty"`
	LeaseSource            *string  `json:"leaseSource,omitempty"`
	LeaseType              *string  `json:"leaseType,omitempty"`
	LeaseTypeDescription   *string  `json:"leaseTypeDescription,omitempty"`
	LeaseRateCardNumber    *string  `json:"leaseRateCardNumber,omitempty"`
	ForceIncludeInForecast *bool    `json:"forceIncludeInForecast,omitempty"`
	ForceExcludeInForecast *bool    `json:"forceExcludeInForecast,omitempty"`
	// This field is Read Only.
	Cost *float64 `json:"cost,omitempty"`
	// This field is Read Only.
	RecurringCost             *float64 `json:"recurringCost,omitempty"`
	AgreementType             *string  `json:"agreementType,omitempty"`
	AgreementStartDateDefault *string  `json:"agreementStartDateDefault,omitempty"`
	AdditionalProperties      map[string]interface{}
}

type _QuoteTermView QuoteTermView

// NewQuoteTermView instantiates a new QuoteTermView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteTermView() *QuoteTermView {
	this := QuoteTermView{}
	return &this
}

// NewQuoteTermViewWithDefaults instantiates a new QuoteTermView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteTermViewWithDefaults() *QuoteTermView {
	this := QuoteTermView{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *QuoteTermView) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *QuoteTermView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *QuoteTermView) SetId(v string) {
	o.Id = &v
}

// GetIdQuote returns the IdQuote field value if set, zero value otherwise.
func (o *QuoteTermView) GetIdQuote() string {
	if o == nil || IsNil(o.IdQuote) {
		var ret string
		return ret
	}
	return *o.IdQuote
}

// GetIdQuoteOk returns a tuple with the IdQuote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetIdQuoteOk() (*string, bool) {
	if o == nil || IsNil(o.IdQuote) {
		return nil, false
	}
	return o.IdQuote, true
}

// HasIdQuote returns a boolean if a field has been set.
func (o *QuoteTermView) HasIdQuote() bool {
	if o != nil && !IsNil(o.IdQuote) {
		return true
	}

	return false
}

// SetIdQuote gets a reference to the given string and assigns it to the IdQuote field.
func (o *QuoteTermView) SetIdQuote(v string) {
	o.IdQuote = &v
}

// GetPeriods returns the Periods field value if set, zero value otherwise.
func (o *QuoteTermView) GetPeriods() float64 {
	if o == nil || IsNil(o.Periods) {
		var ret float64
		return ret
	}
	return *o.Periods
}

// GetPeriodsOk returns a tuple with the Periods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetPeriodsOk() (*float64, bool) {
	if o == nil || IsNil(o.Periods) {
		return nil, false
	}
	return o.Periods, true
}

// HasPeriods returns a boolean if a field has been set.
func (o *QuoteTermView) HasPeriods() bool {
	if o != nil && !IsNil(o.Periods) {
		return true
	}

	return false
}

// SetPeriods gets a reference to the given float64 and assigns it to the Periods field.
func (o *QuoteTermView) SetPeriods(v float64) {
	o.Periods = &v
}

// GetInterestRate returns the InterestRate field value if set, zero value otherwise.
func (o *QuoteTermView) GetInterestRate() float64 {
	if o == nil || IsNil(o.InterestRate) {
		var ret float64
		return ret
	}
	return *o.InterestRate
}

// GetInterestRateOk returns a tuple with the InterestRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetInterestRateOk() (*float64, bool) {
	if o == nil || IsNil(o.InterestRate) {
		return nil, false
	}
	return o.InterestRate, true
}

// HasInterestRate returns a boolean if a field has been set.
func (o *QuoteTermView) HasInterestRate() bool {
	if o != nil && !IsNil(o.InterestRate) {
		return true
	}

	return false
}

// SetInterestRate gets a reference to the given float64 and assigns it to the InterestRate field.
func (o *QuoteTermView) SetInterestRate(v float64) {
	o.InterestRate = &v
}

// GetDownPayment returns the DownPayment field value if set, zero value otherwise.
func (o *QuoteTermView) GetDownPayment() float64 {
	if o == nil || IsNil(o.DownPayment) {
		var ret float64
		return ret
	}
	return *o.DownPayment
}

// GetDownPaymentOk returns a tuple with the DownPayment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetDownPaymentOk() (*float64, bool) {
	if o == nil || IsNil(o.DownPayment) {
		return nil, false
	}
	return o.DownPayment, true
}

// HasDownPayment returns a boolean if a field has been set.
func (o *QuoteTermView) HasDownPayment() bool {
	if o != nil && !IsNil(o.DownPayment) {
		return true
	}

	return false
}

// SetDownPayment gets a reference to the given float64 and assigns it to the DownPayment field.
func (o *QuoteTermView) SetDownPayment(v float64) {
	o.DownPayment = &v
}

// GetDiscountAmount returns the DiscountAmount field value if set, zero value otherwise.
func (o *QuoteTermView) GetDiscountAmount() float64 {
	if o == nil || IsNil(o.DiscountAmount) {
		var ret float64
		return ret
	}
	return *o.DiscountAmount
}

// GetDiscountAmountOk returns a tuple with the DiscountAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetDiscountAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.DiscountAmount) {
		return nil, false
	}
	return o.DiscountAmount, true
}

// HasDiscountAmount returns a boolean if a field has been set.
func (o *QuoteTermView) HasDiscountAmount() bool {
	if o != nil && !IsNil(o.DiscountAmount) {
		return true
	}

	return false
}

// SetDiscountAmount gets a reference to the given float64 and assigns it to the DiscountAmount field.
func (o *QuoteTermView) SetDiscountAmount(v float64) {
	o.DiscountAmount = &v
}

// GetDiscountPercent returns the DiscountPercent field value if set, zero value otherwise.
func (o *QuoteTermView) GetDiscountPercent() float64 {
	if o == nil || IsNil(o.DiscountPercent) {
		var ret float64
		return ret
	}
	return *o.DiscountPercent
}

// GetDiscountPercentOk returns a tuple with the DiscountPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetDiscountPercentOk() (*float64, bool) {
	if o == nil || IsNil(o.DiscountPercent) {
		return nil, false
	}
	return o.DiscountPercent, true
}

// HasDiscountPercent returns a boolean if a field has been set.
func (o *QuoteTermView) HasDiscountPercent() bool {
	if o != nil && !IsNil(o.DiscountPercent) {
		return true
	}

	return false
}

// SetDiscountPercent gets a reference to the given float64 and assigns it to the DiscountPercent field.
func (o *QuoteTermView) SetDiscountPercent(v float64) {
	o.DiscountPercent = &v
}

// GetTotalAmount returns the TotalAmount field value if set, zero value otherwise.
func (o *QuoteTermView) GetTotalAmount() float64 {
	if o == nil || IsNil(o.TotalAmount) {
		var ret float64
		return ret
	}
	return *o.TotalAmount
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetTotalAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalAmount) {
		return nil, false
	}
	return o.TotalAmount, true
}

// HasTotalAmount returns a boolean if a field has been set.
func (o *QuoteTermView) HasTotalAmount() bool {
	if o != nil && !IsNil(o.TotalAmount) {
		return true
	}

	return false
}

// SetTotalAmount gets a reference to the given float64 and assigns it to the TotalAmount field.
func (o *QuoteTermView) SetTotalAmount(v float64) {
	o.TotalAmount = &v
}

// GetPrincipal returns the Principal field value if set, zero value otherwise.
func (o *QuoteTermView) GetPrincipal() float64 {
	if o == nil || IsNil(o.Principal) {
		var ret float64
		return ret
	}
	return *o.Principal
}

// GetPrincipalOk returns a tuple with the Principal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetPrincipalOk() (*float64, bool) {
	if o == nil || IsNil(o.Principal) {
		return nil, false
	}
	return o.Principal, true
}

// HasPrincipal returns a boolean if a field has been set.
func (o *QuoteTermView) HasPrincipal() bool {
	if o != nil && !IsNil(o.Principal) {
		return true
	}

	return false
}

// SetPrincipal gets a reference to the given float64 and assigns it to the Principal field.
func (o *QuoteTermView) SetPrincipal(v float64) {
	o.Principal = &v
}

// GetPeriodPaymentAmount returns the PeriodPaymentAmount field value if set, zero value otherwise.
func (o *QuoteTermView) GetPeriodPaymentAmount() float64 {
	if o == nil || IsNil(o.PeriodPaymentAmount) {
		var ret float64
		return ret
	}
	return *o.PeriodPaymentAmount
}

// GetPeriodPaymentAmountOk returns a tuple with the PeriodPaymentAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetPeriodPaymentAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.PeriodPaymentAmount) {
		return nil, false
	}
	return o.PeriodPaymentAmount, true
}

// HasPeriodPaymentAmount returns a boolean if a field has been set.
func (o *QuoteTermView) HasPeriodPaymentAmount() bool {
	if o != nil && !IsNil(o.PeriodPaymentAmount) {
		return true
	}

	return false
}

// SetPeriodPaymentAmount gets a reference to the given float64 and assigns it to the PeriodPaymentAmount field.
func (o *QuoteTermView) SetPeriodPaymentAmount(v float64) {
	o.PeriodPaymentAmount = &v
}

// GetPeriodInterval returns the PeriodInterval field value if set, zero value otherwise.
func (o *QuoteTermView) GetPeriodInterval() string {
	if o == nil || IsNil(o.PeriodInterval) {
		var ret string
		return ret
	}
	return *o.PeriodInterval
}

// GetPeriodIntervalOk returns a tuple with the PeriodInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetPeriodIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.PeriodInterval) {
		return nil, false
	}
	return o.PeriodInterval, true
}

// HasPeriodInterval returns a boolean if a field has been set.
func (o *QuoteTermView) HasPeriodInterval() bool {
	if o != nil && !IsNil(o.PeriodInterval) {
		return true
	}

	return false
}

// SetPeriodInterval gets a reference to the given string and assigns it to the PeriodInterval field.
func (o *QuoteTermView) SetPeriodInterval(v string) {
	o.PeriodInterval = &v
}

// GetIsSelected returns the IsSelected field value if set, zero value otherwise.
func (o *QuoteTermView) GetIsSelected() bool {
	if o == nil || IsNil(o.IsSelected) {
		var ret bool
		return ret
	}
	return *o.IsSelected
}

// GetIsSelectedOk returns a tuple with the IsSelected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetIsSelectedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSelected) {
		return nil, false
	}
	return o.IsSelected, true
}

// HasIsSelected returns a boolean if a field has been set.
func (o *QuoteTermView) HasIsSelected() bool {
	if o != nil && !IsNil(o.IsSelected) {
		return true
	}

	return false
}

// SetIsSelected gets a reference to the given bool and assigns it to the IsSelected field.
func (o *QuoteTermView) SetIsSelected(v bool) {
	o.IsSelected = &v
}

// GetRecurringDiscountAmount returns the RecurringDiscountAmount field value if set, zero value otherwise.
func (o *QuoteTermView) GetRecurringDiscountAmount() float64 {
	if o == nil || IsNil(o.RecurringDiscountAmount) {
		var ret float64
		return ret
	}
	return *o.RecurringDiscountAmount
}

// GetRecurringDiscountAmountOk returns a tuple with the RecurringDiscountAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetRecurringDiscountAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.RecurringDiscountAmount) {
		return nil, false
	}
	return o.RecurringDiscountAmount, true
}

// HasRecurringDiscountAmount returns a boolean if a field has been set.
func (o *QuoteTermView) HasRecurringDiscountAmount() bool {
	if o != nil && !IsNil(o.RecurringDiscountAmount) {
		return true
	}

	return false
}

// SetRecurringDiscountAmount gets a reference to the given float64 and assigns it to the RecurringDiscountAmount field.
func (o *QuoteTermView) SetRecurringDiscountAmount(v float64) {
	o.RecurringDiscountAmount = &v
}

// GetRecurringDiscountPercent returns the RecurringDiscountPercent field value if set, zero value otherwise.
func (o *QuoteTermView) GetRecurringDiscountPercent() float64 {
	if o == nil || IsNil(o.RecurringDiscountPercent) {
		var ret float64
		return ret
	}
	return *o.RecurringDiscountPercent
}

// GetRecurringDiscountPercentOk returns a tuple with the RecurringDiscountPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetRecurringDiscountPercentOk() (*float64, bool) {
	if o == nil || IsNil(o.RecurringDiscountPercent) {
		return nil, false
	}
	return o.RecurringDiscountPercent, true
}

// HasRecurringDiscountPercent returns a boolean if a field has been set.
func (o *QuoteTermView) HasRecurringDiscountPercent() bool {
	if o != nil && !IsNil(o.RecurringDiscountPercent) {
		return true
	}

	return false
}

// SetRecurringDiscountPercent gets a reference to the given float64 and assigns it to the RecurringDiscountPercent field.
func (o *QuoteTermView) SetRecurringDiscountPercent(v float64) {
	o.RecurringDiscountPercent = &v
}

// GetRecurringTotalAmount returns the RecurringTotalAmount field value if set, zero value otherwise.
func (o *QuoteTermView) GetRecurringTotalAmount() float64 {
	if o == nil || IsNil(o.RecurringTotalAmount) {
		var ret float64
		return ret
	}
	return *o.RecurringTotalAmount
}

// GetRecurringTotalAmountOk returns a tuple with the RecurringTotalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetRecurringTotalAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.RecurringTotalAmount) {
		return nil, false
	}
	return o.RecurringTotalAmount, true
}

// HasRecurringTotalAmount returns a boolean if a field has been set.
func (o *QuoteTermView) HasRecurringTotalAmount() bool {
	if o != nil && !IsNil(o.RecurringTotalAmount) {
		return true
	}

	return false
}

// SetRecurringTotalAmount gets a reference to the given float64 and assigns it to the RecurringTotalAmount field.
func (o *QuoteTermView) SetRecurringTotalAmount(v float64) {
	o.RecurringTotalAmount = &v
}

// GetFinancingGroup returns the FinancingGroup field value if set, zero value otherwise.
func (o *QuoteTermView) GetFinancingGroup() string {
	if o == nil || IsNil(o.FinancingGroup) {
		var ret string
		return ret
	}
	return *o.FinancingGroup
}

// GetFinancingGroupOk returns a tuple with the FinancingGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetFinancingGroupOk() (*string, bool) {
	if o == nil || IsNil(o.FinancingGroup) {
		return nil, false
	}
	return o.FinancingGroup, true
}

// HasFinancingGroup returns a boolean if a field has been set.
func (o *QuoteTermView) HasFinancingGroup() bool {
	if o != nil && !IsNil(o.FinancingGroup) {
		return true
	}

	return false
}

// SetFinancingGroup gets a reference to the given string and assigns it to the FinancingGroup field.
func (o *QuoteTermView) SetFinancingGroup(v string) {
	o.FinancingGroup = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *QuoteTermView) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *QuoteTermView) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *QuoteTermView) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *QuoteTermView) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *QuoteTermView) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *QuoteTermView) SetDescription(v string) {
	o.Description = &v
}

// GetRecurringBeforeDiscount returns the RecurringBeforeDiscount field value if set, zero value otherwise.
func (o *QuoteTermView) GetRecurringBeforeDiscount() float64 {
	if o == nil || IsNil(o.RecurringBeforeDiscount) {
		var ret float64
		return ret
	}
	return *o.RecurringBeforeDiscount
}

// GetRecurringBeforeDiscountOk returns a tuple with the RecurringBeforeDiscount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetRecurringBeforeDiscountOk() (*float64, bool) {
	if o == nil || IsNil(o.RecurringBeforeDiscount) {
		return nil, false
	}
	return o.RecurringBeforeDiscount, true
}

// HasRecurringBeforeDiscount returns a boolean if a field has been set.
func (o *QuoteTermView) HasRecurringBeforeDiscount() bool {
	if o != nil && !IsNil(o.RecurringBeforeDiscount) {
		return true
	}

	return false
}

// SetRecurringBeforeDiscount gets a reference to the given float64 and assigns it to the RecurringBeforeDiscount field.
func (o *QuoteTermView) SetRecurringBeforeDiscount(v float64) {
	o.RecurringBeforeDiscount = &v
}

// GetTabGroup returns the TabGroup field value if set, zero value otherwise.
func (o *QuoteTermView) GetTabGroup() string {
	if o == nil || IsNil(o.TabGroup) {
		var ret string
		return ret
	}
	return *o.TabGroup
}

// GetTabGroupOk returns a tuple with the TabGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetTabGroupOk() (*string, bool) {
	if o == nil || IsNil(o.TabGroup) {
		return nil, false
	}
	return o.TabGroup, true
}

// HasTabGroup returns a boolean if a field has been set.
func (o *QuoteTermView) HasTabGroup() bool {
	if o != nil && !IsNil(o.TabGroup) {
		return true
	}

	return false
}

// SetTabGroup gets a reference to the given string and assigns it to the TabGroup field.
func (o *QuoteTermView) SetTabGroup(v string) {
	o.TabGroup = &v
}

// GetGroupSort returns the GroupSort field value if set, zero value otherwise.
func (o *QuoteTermView) GetGroupSort() float64 {
	if o == nil || IsNil(o.GroupSort) {
		var ret float64
		return ret
	}
	return *o.GroupSort
}

// GetGroupSortOk returns a tuple with the GroupSort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetGroupSortOk() (*float64, bool) {
	if o == nil || IsNil(o.GroupSort) {
		return nil, false
	}
	return o.GroupSort, true
}

// HasGroupSort returns a boolean if a field has been set.
func (o *QuoteTermView) HasGroupSort() bool {
	if o != nil && !IsNil(o.GroupSort) {
		return true
	}

	return false
}

// SetGroupSort gets a reference to the given float64 and assigns it to the GroupSort field.
func (o *QuoteTermView) SetGroupSort(v float64) {
	o.GroupSort = &v
}

// GetNameSort returns the NameSort field value if set, zero value otherwise.
func (o *QuoteTermView) GetNameSort() float64 {
	if o == nil || IsNil(o.NameSort) {
		var ret float64
		return ret
	}
	return *o.NameSort
}

// GetNameSortOk returns a tuple with the NameSort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetNameSortOk() (*float64, bool) {
	if o == nil || IsNil(o.NameSort) {
		return nil, false
	}
	return o.NameSort, true
}

// HasNameSort returns a boolean if a field has been set.
func (o *QuoteTermView) HasNameSort() bool {
	if o != nil && !IsNil(o.NameSort) {
		return true
	}

	return false
}

// SetNameSort gets a reference to the given float64 and assigns it to the NameSort field.
func (o *QuoteTermView) SetNameSort(v float64) {
	o.NameSort = &v
}

// GetTabName returns the TabName field value if set, zero value otherwise.
func (o *QuoteTermView) GetTabName() string {
	if o == nil || IsNil(o.TabName) {
		var ret string
		return ret
	}
	return *o.TabName
}

// GetTabNameOk returns a tuple with the TabName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetTabNameOk() (*string, bool) {
	if o == nil || IsNil(o.TabName) {
		return nil, false
	}
	return o.TabName, true
}

// HasTabName returns a boolean if a field has been set.
func (o *QuoteTermView) HasTabName() bool {
	if o != nil && !IsNil(o.TabName) {
		return true
	}

	return false
}

// SetTabName gets a reference to the given string and assigns it to the TabName field.
func (o *QuoteTermView) SetTabName(v string) {
	o.TabName = &v
}

// GetTotalAmountOverride returns the TotalAmountOverride field value if set, zero value otherwise.
func (o *QuoteTermView) GetTotalAmountOverride() float64 {
	if o == nil || IsNil(o.TotalAmountOverride) {
		var ret float64
		return ret
	}
	return *o.TotalAmountOverride
}

// GetTotalAmountOverrideOk returns a tuple with the TotalAmountOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetTotalAmountOverrideOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalAmountOverride) {
		return nil, false
	}
	return o.TotalAmountOverride, true
}

// HasTotalAmountOverride returns a boolean if a field has been set.
func (o *QuoteTermView) HasTotalAmountOverride() bool {
	if o != nil && !IsNil(o.TotalAmountOverride) {
		return true
	}

	return false
}

// SetTotalAmountOverride gets a reference to the given float64 and assigns it to the TotalAmountOverride field.
func (o *QuoteTermView) SetTotalAmountOverride(v float64) {
	o.TotalAmountOverride = &v
}

// GetRecurringTotalAmountOverride returns the RecurringTotalAmountOverride field value if set, zero value otherwise.
func (o *QuoteTermView) GetRecurringTotalAmountOverride() float64 {
	if o == nil || IsNil(o.RecurringTotalAmountOverride) {
		var ret float64
		return ret
	}
	return *o.RecurringTotalAmountOverride
}

// GetRecurringTotalAmountOverrideOk returns a tuple with the RecurringTotalAmountOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetRecurringTotalAmountOverrideOk() (*float64, bool) {
	if o == nil || IsNil(o.RecurringTotalAmountOverride) {
		return nil, false
	}
	return o.RecurringTotalAmountOverride, true
}

// HasRecurringTotalAmountOverride returns a boolean if a field has been set.
func (o *QuoteTermView) HasRecurringTotalAmountOverride() bool {
	if o != nil && !IsNil(o.RecurringTotalAmountOverride) {
		return true
	}

	return false
}

// SetRecurringTotalAmountOverride gets a reference to the given float64 and assigns it to the RecurringTotalAmountOverride field.
func (o *QuoteTermView) SetRecurringTotalAmountOverride(v float64) {
	o.RecurringTotalAmountOverride = &v
}

// GetIdRecurringRevenue returns the IdRecurringRevenue field value if set, zero value otherwise.
func (o *QuoteTermView) GetIdRecurringRevenue() string {
	if o == nil || IsNil(o.IdRecurringRevenue) {
		var ret string
		return ret
	}
	return *o.IdRecurringRevenue
}

// GetIdRecurringRevenueOk returns a tuple with the IdRecurringRevenue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetIdRecurringRevenueOk() (*string, bool) {
	if o == nil || IsNil(o.IdRecurringRevenue) {
		return nil, false
	}
	return o.IdRecurringRevenue, true
}

// HasIdRecurringRevenue returns a boolean if a field has been set.
func (o *QuoteTermView) HasIdRecurringRevenue() bool {
	if o != nil && !IsNil(o.IdRecurringRevenue) {
		return true
	}

	return false
}

// SetIdRecurringRevenue gets a reference to the given string and assigns it to the IdRecurringRevenue field.
func (o *QuoteTermView) SetIdRecurringRevenue(v string) {
	o.IdRecurringRevenue = &v
}

// GetRecurringPeriods returns the RecurringPeriods field value if set, zero value otherwise.
func (o *QuoteTermView) GetRecurringPeriods() float64 {
	if o == nil || IsNil(o.RecurringPeriods) {
		var ret float64
		return ret
	}
	return *o.RecurringPeriods
}

// GetRecurringPeriodsOk returns a tuple with the RecurringPeriods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetRecurringPeriodsOk() (*float64, bool) {
	if o == nil || IsNil(o.RecurringPeriods) {
		return nil, false
	}
	return o.RecurringPeriods, true
}

// HasRecurringPeriods returns a boolean if a field has been set.
func (o *QuoteTermView) HasRecurringPeriods() bool {
	if o != nil && !IsNil(o.RecurringPeriods) {
		return true
	}

	return false
}

// SetRecurringPeriods gets a reference to the given float64 and assigns it to the RecurringPeriods field.
func (o *QuoteTermView) SetRecurringPeriods(v float64) {
	o.RecurringPeriods = &v
}

// GetRecurringTotalAggregated returns the RecurringTotalAggregated field value if set, zero value otherwise.
func (o *QuoteTermView) GetRecurringTotalAggregated() float64 {
	if o == nil || IsNil(o.RecurringTotalAggregated) {
		var ret float64
		return ret
	}
	return *o.RecurringTotalAggregated
}

// GetRecurringTotalAggregatedOk returns a tuple with the RecurringTotalAggregated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetRecurringTotalAggregatedOk() (*float64, bool) {
	if o == nil || IsNil(o.RecurringTotalAggregated) {
		return nil, false
	}
	return o.RecurringTotalAggregated, true
}

// HasRecurringTotalAggregated returns a boolean if a field has been set.
func (o *QuoteTermView) HasRecurringTotalAggregated() bool {
	if o != nil && !IsNil(o.RecurringTotalAggregated) {
		return true
	}

	return false
}

// SetRecurringTotalAggregated gets a reference to the given float64 and assigns it to the RecurringTotalAggregated field.
func (o *QuoteTermView) SetRecurringTotalAggregated(v float64) {
	o.RecurringTotalAggregated = &v
}

// GetSubscriptionName returns the SubscriptionName field value if set, zero value otherwise.
func (o *QuoteTermView) GetSubscriptionName() string {
	if o == nil || IsNil(o.SubscriptionName) {
		var ret string
		return ret
	}
	return *o.SubscriptionName
}

// GetSubscriptionNameOk returns a tuple with the SubscriptionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetSubscriptionNameOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionName) {
		return nil, false
	}
	return o.SubscriptionName, true
}

// HasSubscriptionName returns a boolean if a field has been set.
func (o *QuoteTermView) HasSubscriptionName() bool {
	if o != nil && !IsNil(o.SubscriptionName) {
		return true
	}

	return false
}

// SetSubscriptionName gets a reference to the given string and assigns it to the SubscriptionName field.
func (o *QuoteTermView) SetSubscriptionName(v string) {
	o.SubscriptionName = &v
}

// GetIsAutomaticallyBillable returns the IsAutomaticallyBillable field value if set, zero value otherwise.
func (o *QuoteTermView) GetIsAutomaticallyBillable() bool {
	if o == nil || IsNil(o.IsAutomaticallyBillable) {
		var ret bool
		return ret
	}
	return *o.IsAutomaticallyBillable
}

// GetIsAutomaticallyBillableOk returns a tuple with the IsAutomaticallyBillable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetIsAutomaticallyBillableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAutomaticallyBillable) {
		return nil, false
	}
	return o.IsAutomaticallyBillable, true
}

// HasIsAutomaticallyBillable returns a boolean if a field has been set.
func (o *QuoteTermView) HasIsAutomaticallyBillable() bool {
	if o != nil && !IsNil(o.IsAutomaticallyBillable) {
		return true
	}

	return false
}

// SetIsAutomaticallyBillable gets a reference to the given bool and assigns it to the IsAutomaticallyBillable field.
func (o *QuoteTermView) SetIsAutomaticallyBillable(v bool) {
	o.IsAutomaticallyBillable = &v
}

// GetOverrideStartDate returns the OverrideStartDate field value if set, zero value otherwise.
func (o *QuoteTermView) GetOverrideStartDate() time.Time {
	if o == nil || IsNil(o.OverrideStartDate) {
		var ret time.Time
		return ret
	}
	return *o.OverrideStartDate
}

// GetOverrideStartDateOk returns a tuple with the OverrideStartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetOverrideStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OverrideStartDate) {
		return nil, false
	}
	return o.OverrideStartDate, true
}

// HasOverrideStartDate returns a boolean if a field has been set.
func (o *QuoteTermView) HasOverrideStartDate() bool {
	if o != nil && !IsNil(o.OverrideStartDate) {
		return true
	}

	return false
}

// SetOverrideStartDate gets a reference to the given time.Time and assigns it to the OverrideStartDate field.
func (o *QuoteTermView) SetOverrideStartDate(v time.Time) {
	o.OverrideStartDate = &v
}

// GetStartDateMode returns the StartDateMode field value if set, zero value otherwise.
func (o *QuoteTermView) GetStartDateMode() string {
	if o == nil || IsNil(o.StartDateMode) {
		var ret string
		return ret
	}
	return *o.StartDateMode
}

// GetStartDateModeOk returns a tuple with the StartDateMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetStartDateModeOk() (*string, bool) {
	if o == nil || IsNil(o.StartDateMode) {
		return nil, false
	}
	return o.StartDateMode, true
}

// HasStartDateMode returns a boolean if a field has been set.
func (o *QuoteTermView) HasStartDateMode() bool {
	if o != nil && !IsNil(o.StartDateMode) {
		return true
	}

	return false
}

// SetStartDateMode gets a reference to the given string and assigns it to the StartDateMode field.
func (o *QuoteTermView) SetStartDateMode(v string) {
	o.StartDateMode = &v
}

// GetAuthorizeNetIntervalUnit returns the AuthorizeNetIntervalUnit field value if set, zero value otherwise.
func (o *QuoteTermView) GetAuthorizeNetIntervalUnit() string {
	if o == nil || IsNil(o.AuthorizeNetIntervalUnit) {
		var ret string
		return ret
	}
	return *o.AuthorizeNetIntervalUnit
}

// GetAuthorizeNetIntervalUnitOk returns a tuple with the AuthorizeNetIntervalUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetAuthorizeNetIntervalUnitOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorizeNetIntervalUnit) {
		return nil, false
	}
	return o.AuthorizeNetIntervalUnit, true
}

// HasAuthorizeNetIntervalUnit returns a boolean if a field has been set.
func (o *QuoteTermView) HasAuthorizeNetIntervalUnit() bool {
	if o != nil && !IsNil(o.AuthorizeNetIntervalUnit) {
		return true
	}

	return false
}

// SetAuthorizeNetIntervalUnit gets a reference to the given string and assigns it to the AuthorizeNetIntervalUnit field.
func (o *QuoteTermView) SetAuthorizeNetIntervalUnit(v string) {
	o.AuthorizeNetIntervalUnit = &v
}

// GetAuthorizeNetIntervalLength returns the AuthorizeNetIntervalLength field value if set, zero value otherwise.
func (o *QuoteTermView) GetAuthorizeNetIntervalLength() int32 {
	if o == nil || IsNil(o.AuthorizeNetIntervalLength) {
		var ret int32
		return ret
	}
	return *o.AuthorizeNetIntervalLength
}

// GetAuthorizeNetIntervalLengthOk returns a tuple with the AuthorizeNetIntervalLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetAuthorizeNetIntervalLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.AuthorizeNetIntervalLength) {
		return nil, false
	}
	return o.AuthorizeNetIntervalLength, true
}

// HasAuthorizeNetIntervalLength returns a boolean if a field has been set.
func (o *QuoteTermView) HasAuthorizeNetIntervalLength() bool {
	if o != nil && !IsNil(o.AuthorizeNetIntervalLength) {
		return true
	}

	return false
}

// SetAuthorizeNetIntervalLength gets a reference to the given int32 and assigns it to the AuthorizeNetIntervalLength field.
func (o *QuoteTermView) SetAuthorizeNetIntervalLength(v int32) {
	o.AuthorizeNetIntervalLength = &v
}

// GetAuthorizeNetTotalOccurances returns the AuthorizeNetTotalOccurances field value if set, zero value otherwise.
func (o *QuoteTermView) GetAuthorizeNetTotalOccurances() int32 {
	if o == nil || IsNil(o.AuthorizeNetTotalOccurances) {
		var ret int32
		return ret
	}
	return *o.AuthorizeNetTotalOccurances
}

// GetAuthorizeNetTotalOccurancesOk returns a tuple with the AuthorizeNetTotalOccurances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetAuthorizeNetTotalOccurancesOk() (*int32, bool) {
	if o == nil || IsNil(o.AuthorizeNetTotalOccurances) {
		return nil, false
	}
	return o.AuthorizeNetTotalOccurances, true
}

// HasAuthorizeNetTotalOccurances returns a boolean if a field has been set.
func (o *QuoteTermView) HasAuthorizeNetTotalOccurances() bool {
	if o != nil && !IsNil(o.AuthorizeNetTotalOccurances) {
		return true
	}

	return false
}

// SetAuthorizeNetTotalOccurances gets a reference to the given int32 and assigns it to the AuthorizeNetTotalOccurances field.
func (o *QuoteTermView) SetAuthorizeNetTotalOccurances(v int32) {
	o.AuthorizeNetTotalOccurances = &v
}

// GetIntervalToStart returns the IntervalToStart field value if set, zero value otherwise.
func (o *QuoteTermView) GetIntervalToStart() int32 {
	if o == nil || IsNil(o.IntervalToStart) {
		var ret int32
		return ret
	}
	return *o.IntervalToStart
}

// GetIntervalToStartOk returns a tuple with the IntervalToStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetIntervalToStartOk() (*int32, bool) {
	if o == nil || IsNil(o.IntervalToStart) {
		return nil, false
	}
	return o.IntervalToStart, true
}

// HasIntervalToStart returns a boolean if a field has been set.
func (o *QuoteTermView) HasIntervalToStart() bool {
	if o != nil && !IsNil(o.IntervalToStart) {
		return true
	}

	return false
}

// SetIntervalToStart gets a reference to the given int32 and assigns it to the IntervalToStart field.
func (o *QuoteTermView) SetIntervalToStart(v int32) {
	o.IntervalToStart = &v
}

// GetOppRecurringAsAdjustment returns the OppRecurringAsAdjustment field value if set, zero value otherwise.
func (o *QuoteTermView) GetOppRecurringAsAdjustment() bool {
	if o == nil || IsNil(o.OppRecurringAsAdjustment) {
		var ret bool
		return ret
	}
	return *o.OppRecurringAsAdjustment
}

// GetOppRecurringAsAdjustmentOk returns a tuple with the OppRecurringAsAdjustment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetOppRecurringAsAdjustmentOk() (*bool, bool) {
	if o == nil || IsNil(o.OppRecurringAsAdjustment) {
		return nil, false
	}
	return o.OppRecurringAsAdjustment, true
}

// HasOppRecurringAsAdjustment returns a boolean if a field has been set.
func (o *QuoteTermView) HasOppRecurringAsAdjustment() bool {
	if o != nil && !IsNil(o.OppRecurringAsAdjustment) {
		return true
	}

	return false
}

// SetOppRecurringAsAdjustment gets a reference to the given bool and assigns it to the OppRecurringAsAdjustment field.
func (o *QuoteTermView) SetOppRecurringAsAdjustment(v bool) {
	o.OppRecurringAsAdjustment = &v
}

// GetSpreadOneTime returns the SpreadOneTime field value if set, zero value otherwise.
func (o *QuoteTermView) GetSpreadOneTime() bool {
	if o == nil || IsNil(o.SpreadOneTime) {
		var ret bool
		return ret
	}
	return *o.SpreadOneTime
}

// GetSpreadOneTimeOk returns a tuple with the SpreadOneTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetSpreadOneTimeOk() (*bool, bool) {
	if o == nil || IsNil(o.SpreadOneTime) {
		return nil, false
	}
	return o.SpreadOneTime, true
}

// HasSpreadOneTime returns a boolean if a field has been set.
func (o *QuoteTermView) HasSpreadOneTime() bool {
	if o != nil && !IsNil(o.SpreadOneTime) {
		return true
	}

	return false
}

// SetSpreadOneTime gets a reference to the given bool and assigns it to the SpreadOneTime field.
func (o *QuoteTermView) SetSpreadOneTime(v bool) {
	o.SpreadOneTime = &v
}

// GetIsPrinted returns the IsPrinted field value if set, zero value otherwise.
func (o *QuoteTermView) GetIsPrinted() bool {
	if o == nil || IsNil(o.IsPrinted) {
		var ret bool
		return ret
	}
	return *o.IsPrinted
}

// GetIsPrintedOk returns a tuple with the IsPrinted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetIsPrintedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPrinted) {
		return nil, false
	}
	return o.IsPrinted, true
}

// HasIsPrinted returns a boolean if a field has been set.
func (o *QuoteTermView) HasIsPrinted() bool {
	if o != nil && !IsNil(o.IsPrinted) {
		return true
	}

	return false
}

// SetIsPrinted gets a reference to the given bool and assigns it to the IsPrinted field.
func (o *QuoteTermView) SetIsPrinted(v bool) {
	o.IsPrinted = &v
}

// GetRecurringRevenueLabel returns the RecurringRevenueLabel field value if set, zero value otherwise.
func (o *QuoteTermView) GetRecurringRevenueLabel() string {
	if o == nil || IsNil(o.RecurringRevenueLabel) {
		var ret string
		return ret
	}
	return *o.RecurringRevenueLabel
}

// GetRecurringRevenueLabelOk returns a tuple with the RecurringRevenueLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetRecurringRevenueLabelOk() (*string, bool) {
	if o == nil || IsNil(o.RecurringRevenueLabel) {
		return nil, false
	}
	return o.RecurringRevenueLabel, true
}

// HasRecurringRevenueLabel returns a boolean if a field has been set.
func (o *QuoteTermView) HasRecurringRevenueLabel() bool {
	if o != nil && !IsNil(o.RecurringRevenueLabel) {
		return true
	}

	return false
}

// SetRecurringRevenueLabel gets a reference to the given string and assigns it to the RecurringRevenueLabel field.
func (o *QuoteTermView) SetRecurringRevenueLabel(v string) {
	o.RecurringRevenueLabel = &v
}

// GetTabExcludeFilter returns the TabExcludeFilter field value if set, zero value otherwise.
func (o *QuoteTermView) GetTabExcludeFilter() string {
	if o == nil || IsNil(o.TabExcludeFilter) {
		var ret string
		return ret
	}
	return *o.TabExcludeFilter
}

// GetTabExcludeFilterOk returns a tuple with the TabExcludeFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetTabExcludeFilterOk() (*string, bool) {
	if o == nil || IsNil(o.TabExcludeFilter) {
		return nil, false
	}
	return o.TabExcludeFilter, true
}

// HasTabExcludeFilter returns a boolean if a field has been set.
func (o *QuoteTermView) HasTabExcludeFilter() bool {
	if o != nil && !IsNil(o.TabExcludeFilter) {
		return true
	}

	return false
}

// SetTabExcludeFilter gets a reference to the given string and assigns it to the TabExcludeFilter field.
func (o *QuoteTermView) SetTabExcludeFilter(v string) {
	o.TabExcludeFilter = &v
}

// GetTabIncludeFilter returns the TabIncludeFilter field value if set, zero value otherwise.
func (o *QuoteTermView) GetTabIncludeFilter() string {
	if o == nil || IsNil(o.TabIncludeFilter) {
		var ret string
		return ret
	}
	return *o.TabIncludeFilter
}

// GetTabIncludeFilterOk returns a tuple with the TabIncludeFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetTabIncludeFilterOk() (*string, bool) {
	if o == nil || IsNil(o.TabIncludeFilter) {
		return nil, false
	}
	return o.TabIncludeFilter, true
}

// HasTabIncludeFilter returns a boolean if a field has been set.
func (o *QuoteTermView) HasTabIncludeFilter() bool {
	if o != nil && !IsNil(o.TabIncludeFilter) {
		return true
	}

	return false
}

// SetTabIncludeFilter gets a reference to the given string and assigns it to the TabIncludeFilter field.
func (o *QuoteTermView) SetTabIncludeFilter(v string) {
	o.TabIncludeFilter = &v
}

// GetIsRoundedPayments returns the IsRoundedPayments field value if set, zero value otherwise.
func (o *QuoteTermView) GetIsRoundedPayments() bool {
	if o == nil || IsNil(o.IsRoundedPayments) {
		var ret bool
		return ret
	}
	return *o.IsRoundedPayments
}

// GetIsRoundedPaymentsOk returns a tuple with the IsRoundedPayments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetIsRoundedPaymentsOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRoundedPayments) {
		return nil, false
	}
	return o.IsRoundedPayments, true
}

// HasIsRoundedPayments returns a boolean if a field has been set.
func (o *QuoteTermView) HasIsRoundedPayments() bool {
	if o != nil && !IsNil(o.IsRoundedPayments) {
		return true
	}

	return false
}

// SetIsRoundedPayments gets a reference to the given bool and assigns it to the IsRoundedPayments field.
func (o *QuoteTermView) SetIsRoundedPayments(v bool) {
	o.IsRoundedPayments = &v
}

// GetObeyStandardTabFilters returns the ObeyStandardTabFilters field value if set, zero value otherwise.
func (o *QuoteTermView) GetObeyStandardTabFilters() bool {
	if o == nil || IsNil(o.ObeyStandardTabFilters) {
		var ret bool
		return ret
	}
	return *o.ObeyStandardTabFilters
}

// GetObeyStandardTabFiltersOk returns a tuple with the ObeyStandardTabFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetObeyStandardTabFiltersOk() (*bool, bool) {
	if o == nil || IsNil(o.ObeyStandardTabFilters) {
		return nil, false
	}
	return o.ObeyStandardTabFilters, true
}

// HasObeyStandardTabFilters returns a boolean if a field has been set.
func (o *QuoteTermView) HasObeyStandardTabFilters() bool {
	if o != nil && !IsNil(o.ObeyStandardTabFilters) {
		return true
	}

	return false
}

// SetObeyStandardTabFilters gets a reference to the given bool and assigns it to the ObeyStandardTabFilters field.
func (o *QuoteTermView) SetObeyStandardTabFilters(v bool) {
	o.ObeyStandardTabFilters = &v
}

// GetLeasingName returns the LeasingName field value if set, zero value otherwise.
func (o *QuoteTermView) GetLeasingName() string {
	if o == nil || IsNil(o.LeasingName) {
		var ret string
		return ret
	}
	return *o.LeasingName
}

// GetLeasingNameOk returns a tuple with the LeasingName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetLeasingNameOk() (*string, bool) {
	if o == nil || IsNil(o.LeasingName) {
		return nil, false
	}
	return o.LeasingName, true
}

// HasLeasingName returns a boolean if a field has been set.
func (o *QuoteTermView) HasLeasingName() bool {
	if o != nil && !IsNil(o.LeasingName) {
		return true
	}

	return false
}

// SetLeasingName gets a reference to the given string and assigns it to the LeasingName field.
func (o *QuoteTermView) SetLeasingName(v string) {
	o.LeasingName = &v
}

// GetLeasingRate returns the LeasingRate field value if set, zero value otherwise.
func (o *QuoteTermView) GetLeasingRate() float64 {
	if o == nil || IsNil(o.LeasingRate) {
		var ret float64
		return ret
	}
	return *o.LeasingRate
}

// GetLeasingRateOk returns a tuple with the LeasingRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetLeasingRateOk() (*float64, bool) {
	if o == nil || IsNil(o.LeasingRate) {
		return nil, false
	}
	return o.LeasingRate, true
}

// HasLeasingRate returns a boolean if a field has been set.
func (o *QuoteTermView) HasLeasingRate() bool {
	if o != nil && !IsNil(o.LeasingRate) {
		return true
	}

	return false
}

// SetLeasingRate gets a reference to the given float64 and assigns it to the LeasingRate field.
func (o *QuoteTermView) SetLeasingRate(v float64) {
	o.LeasingRate = &v
}

// GetLeasingRateOverride returns the LeasingRateOverride field value if set, zero value otherwise.
func (o *QuoteTermView) GetLeasingRateOverride() float64 {
	if o == nil || IsNil(o.LeasingRateOverride) {
		var ret float64
		return ret
	}
	return *o.LeasingRateOverride
}

// GetLeasingRateOverrideOk returns a tuple with the LeasingRateOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetLeasingRateOverrideOk() (*float64, bool) {
	if o == nil || IsNil(o.LeasingRateOverride) {
		return nil, false
	}
	return o.LeasingRateOverride, true
}

// HasLeasingRateOverride returns a boolean if a field has been set.
func (o *QuoteTermView) HasLeasingRateOverride() bool {
	if o != nil && !IsNil(o.LeasingRateOverride) {
		return true
	}

	return false
}

// SetLeasingRateOverride gets a reference to the given float64 and assigns it to the LeasingRateOverride field.
func (o *QuoteTermView) SetLeasingRateOverride(v float64) {
	o.LeasingRateOverride = &v
}

// GetIsLease returns the IsLease field value if set, zero value otherwise.
func (o *QuoteTermView) GetIsLease() bool {
	if o == nil || IsNil(o.IsLease) {
		var ret bool
		return ret
	}
	return *o.IsLease
}

// GetIsLeaseOk returns a tuple with the IsLease field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetIsLeaseOk() (*bool, bool) {
	if o == nil || IsNil(o.IsLease) {
		return nil, false
	}
	return o.IsLease, true
}

// HasIsLease returns a boolean if a field has been set.
func (o *QuoteTermView) HasIsLease() bool {
	if o != nil && !IsNil(o.IsLease) {
		return true
	}

	return false
}

// SetIsLease gets a reference to the given bool and assigns it to the IsLease field.
func (o *QuoteTermView) SetIsLease(v bool) {
	o.IsLease = &v
}

// GetLeaseMonthlyAmount returns the LeaseMonthlyAmount field value if set, zero value otherwise.
func (o *QuoteTermView) GetLeaseMonthlyAmount() float64 {
	if o == nil || IsNil(o.LeaseMonthlyAmount) {
		var ret float64
		return ret
	}
	return *o.LeaseMonthlyAmount
}

// GetLeaseMonthlyAmountOk returns a tuple with the LeaseMonthlyAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetLeaseMonthlyAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.LeaseMonthlyAmount) {
		return nil, false
	}
	return o.LeaseMonthlyAmount, true
}

// HasLeaseMonthlyAmount returns a boolean if a field has been set.
func (o *QuoteTermView) HasLeaseMonthlyAmount() bool {
	if o != nil && !IsNil(o.LeaseMonthlyAmount) {
		return true
	}

	return false
}

// SetLeaseMonthlyAmount gets a reference to the given float64 and assigns it to the LeaseMonthlyAmount field.
func (o *QuoteTermView) SetLeaseMonthlyAmount(v float64) {
	o.LeaseMonthlyAmount = &v
}

// GetLeaseDownPayment returns the LeaseDownPayment field value if set, zero value otherwise.
func (o *QuoteTermView) GetLeaseDownPayment() float64 {
	if o == nil || IsNil(o.LeaseDownPayment) {
		var ret float64
		return ret
	}
	return *o.LeaseDownPayment
}

// GetLeaseDownPaymentOk returns a tuple with the LeaseDownPayment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetLeaseDownPaymentOk() (*float64, bool) {
	if o == nil || IsNil(o.LeaseDownPayment) {
		return nil, false
	}
	return o.LeaseDownPayment, true
}

// HasLeaseDownPayment returns a boolean if a field has been set.
func (o *QuoteTermView) HasLeaseDownPayment() bool {
	if o != nil && !IsNil(o.LeaseDownPayment) {
		return true
	}

	return false
}

// SetLeaseDownPayment gets a reference to the given float64 and assigns it to the LeaseDownPayment field.
func (o *QuoteTermView) SetLeaseDownPayment(v float64) {
	o.LeaseDownPayment = &v
}

// GetIdLeasingRates returns the IdLeasingRates field value if set, zero value otherwise.
func (o *QuoteTermView) GetIdLeasingRates() string {
	if o == nil || IsNil(o.IdLeasingRates) {
		var ret string
		return ret
	}
	return *o.IdLeasingRates
}

// GetIdLeasingRatesOk returns a tuple with the IdLeasingRates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetIdLeasingRatesOk() (*string, bool) {
	if o == nil || IsNil(o.IdLeasingRates) {
		return nil, false
	}
	return o.IdLeasingRates, true
}

// HasIdLeasingRates returns a boolean if a field has been set.
func (o *QuoteTermView) HasIdLeasingRates() bool {
	if o != nil && !IsNil(o.IdLeasingRates) {
		return true
	}

	return false
}

// SetIdLeasingRates gets a reference to the given string and assigns it to the IdLeasingRates field.
func (o *QuoteTermView) SetIdLeasingRates(v string) {
	o.IdLeasingRates = &v
}

// GetLeaseSource returns the LeaseSource field value if set, zero value otherwise.
func (o *QuoteTermView) GetLeaseSource() string {
	if o == nil || IsNil(o.LeaseSource) {
		var ret string
		return ret
	}
	return *o.LeaseSource
}

// GetLeaseSourceOk returns a tuple with the LeaseSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetLeaseSourceOk() (*string, bool) {
	if o == nil || IsNil(o.LeaseSource) {
		return nil, false
	}
	return o.LeaseSource, true
}

// HasLeaseSource returns a boolean if a field has been set.
func (o *QuoteTermView) HasLeaseSource() bool {
	if o != nil && !IsNil(o.LeaseSource) {
		return true
	}

	return false
}

// SetLeaseSource gets a reference to the given string and assigns it to the LeaseSource field.
func (o *QuoteTermView) SetLeaseSource(v string) {
	o.LeaseSource = &v
}

// GetLeaseType returns the LeaseType field value if set, zero value otherwise.
func (o *QuoteTermView) GetLeaseType() string {
	if o == nil || IsNil(o.LeaseType) {
		var ret string
		return ret
	}
	return *o.LeaseType
}

// GetLeaseTypeOk returns a tuple with the LeaseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetLeaseTypeOk() (*string, bool) {
	if o == nil || IsNil(o.LeaseType) {
		return nil, false
	}
	return o.LeaseType, true
}

// HasLeaseType returns a boolean if a field has been set.
func (o *QuoteTermView) HasLeaseType() bool {
	if o != nil && !IsNil(o.LeaseType) {
		return true
	}

	return false
}

// SetLeaseType gets a reference to the given string and assigns it to the LeaseType field.
func (o *QuoteTermView) SetLeaseType(v string) {
	o.LeaseType = &v
}

// GetLeaseTypeDescription returns the LeaseTypeDescription field value if set, zero value otherwise.
func (o *QuoteTermView) GetLeaseTypeDescription() string {
	if o == nil || IsNil(o.LeaseTypeDescription) {
		var ret string
		return ret
	}
	return *o.LeaseTypeDescription
}

// GetLeaseTypeDescriptionOk returns a tuple with the LeaseTypeDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetLeaseTypeDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.LeaseTypeDescription) {
		return nil, false
	}
	return o.LeaseTypeDescription, true
}

// HasLeaseTypeDescription returns a boolean if a field has been set.
func (o *QuoteTermView) HasLeaseTypeDescription() bool {
	if o != nil && !IsNil(o.LeaseTypeDescription) {
		return true
	}

	return false
}

// SetLeaseTypeDescription gets a reference to the given string and assigns it to the LeaseTypeDescription field.
func (o *QuoteTermView) SetLeaseTypeDescription(v string) {
	o.LeaseTypeDescription = &v
}

// GetLeaseRateCardNumber returns the LeaseRateCardNumber field value if set, zero value otherwise.
func (o *QuoteTermView) GetLeaseRateCardNumber() string {
	if o == nil || IsNil(o.LeaseRateCardNumber) {
		var ret string
		return ret
	}
	return *o.LeaseRateCardNumber
}

// GetLeaseRateCardNumberOk returns a tuple with the LeaseRateCardNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetLeaseRateCardNumberOk() (*string, bool) {
	if o == nil || IsNil(o.LeaseRateCardNumber) {
		return nil, false
	}
	return o.LeaseRateCardNumber, true
}

// HasLeaseRateCardNumber returns a boolean if a field has been set.
func (o *QuoteTermView) HasLeaseRateCardNumber() bool {
	if o != nil && !IsNil(o.LeaseRateCardNumber) {
		return true
	}

	return false
}

// SetLeaseRateCardNumber gets a reference to the given string and assigns it to the LeaseRateCardNumber field.
func (o *QuoteTermView) SetLeaseRateCardNumber(v string) {
	o.LeaseRateCardNumber = &v
}

// GetForceIncludeInForecast returns the ForceIncludeInForecast field value if set, zero value otherwise.
func (o *QuoteTermView) GetForceIncludeInForecast() bool {
	if o == nil || IsNil(o.ForceIncludeInForecast) {
		var ret bool
		return ret
	}
	return *o.ForceIncludeInForecast
}

// GetForceIncludeInForecastOk returns a tuple with the ForceIncludeInForecast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetForceIncludeInForecastOk() (*bool, bool) {
	if o == nil || IsNil(o.ForceIncludeInForecast) {
		return nil, false
	}
	return o.ForceIncludeInForecast, true
}

// HasForceIncludeInForecast returns a boolean if a field has been set.
func (o *QuoteTermView) HasForceIncludeInForecast() bool {
	if o != nil && !IsNil(o.ForceIncludeInForecast) {
		return true
	}

	return false
}

// SetForceIncludeInForecast gets a reference to the given bool and assigns it to the ForceIncludeInForecast field.
func (o *QuoteTermView) SetForceIncludeInForecast(v bool) {
	o.ForceIncludeInForecast = &v
}

// GetForceExcludeInForecast returns the ForceExcludeInForecast field value if set, zero value otherwise.
func (o *QuoteTermView) GetForceExcludeInForecast() bool {
	if o == nil || IsNil(o.ForceExcludeInForecast) {
		var ret bool
		return ret
	}
	return *o.ForceExcludeInForecast
}

// GetForceExcludeInForecastOk returns a tuple with the ForceExcludeInForecast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetForceExcludeInForecastOk() (*bool, bool) {
	if o == nil || IsNil(o.ForceExcludeInForecast) {
		return nil, false
	}
	return o.ForceExcludeInForecast, true
}

// HasForceExcludeInForecast returns a boolean if a field has been set.
func (o *QuoteTermView) HasForceExcludeInForecast() bool {
	if o != nil && !IsNil(o.ForceExcludeInForecast) {
		return true
	}

	return false
}

// SetForceExcludeInForecast gets a reference to the given bool and assigns it to the ForceExcludeInForecast field.
func (o *QuoteTermView) SetForceExcludeInForecast(v bool) {
	o.ForceExcludeInForecast = &v
}

// GetCost returns the Cost field value if set, zero value otherwise.
func (o *QuoteTermView) GetCost() float64 {
	if o == nil || IsNil(o.Cost) {
		var ret float64
		return ret
	}
	return *o.Cost
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetCostOk() (*float64, bool) {
	if o == nil || IsNil(o.Cost) {
		return nil, false
	}
	return o.Cost, true
}

// HasCost returns a boolean if a field has been set.
func (o *QuoteTermView) HasCost() bool {
	if o != nil && !IsNil(o.Cost) {
		return true
	}

	return false
}

// SetCost gets a reference to the given float64 and assigns it to the Cost field.
func (o *QuoteTermView) SetCost(v float64) {
	o.Cost = &v
}

// GetRecurringCost returns the RecurringCost field value if set, zero value otherwise.
func (o *QuoteTermView) GetRecurringCost() float64 {
	if o == nil || IsNil(o.RecurringCost) {
		var ret float64
		return ret
	}
	return *o.RecurringCost
}

// GetRecurringCostOk returns a tuple with the RecurringCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetRecurringCostOk() (*float64, bool) {
	if o == nil || IsNil(o.RecurringCost) {
		return nil, false
	}
	return o.RecurringCost, true
}

// HasRecurringCost returns a boolean if a field has been set.
func (o *QuoteTermView) HasRecurringCost() bool {
	if o != nil && !IsNil(o.RecurringCost) {
		return true
	}

	return false
}

// SetRecurringCost gets a reference to the given float64 and assigns it to the RecurringCost field.
func (o *QuoteTermView) SetRecurringCost(v float64) {
	o.RecurringCost = &v
}

// GetAgreementType returns the AgreementType field value if set, zero value otherwise.
func (o *QuoteTermView) GetAgreementType() string {
	if o == nil || IsNil(o.AgreementType) {
		var ret string
		return ret
	}
	return *o.AgreementType
}

// GetAgreementTypeOk returns a tuple with the AgreementType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetAgreementTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AgreementType) {
		return nil, false
	}
	return o.AgreementType, true
}

// HasAgreementType returns a boolean if a field has been set.
func (o *QuoteTermView) HasAgreementType() bool {
	if o != nil && !IsNil(o.AgreementType) {
		return true
	}

	return false
}

// SetAgreementType gets a reference to the given string and assigns it to the AgreementType field.
func (o *QuoteTermView) SetAgreementType(v string) {
	o.AgreementType = &v
}

// GetAgreementStartDateDefault returns the AgreementStartDateDefault field value if set, zero value otherwise.
func (o *QuoteTermView) GetAgreementStartDateDefault() string {
	if o == nil || IsNil(o.AgreementStartDateDefault) {
		var ret string
		return ret
	}
	return *o.AgreementStartDateDefault
}

// GetAgreementStartDateDefaultOk returns a tuple with the AgreementStartDateDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteTermView) GetAgreementStartDateDefaultOk() (*string, bool) {
	if o == nil || IsNil(o.AgreementStartDateDefault) {
		return nil, false
	}
	return o.AgreementStartDateDefault, true
}

// HasAgreementStartDateDefault returns a boolean if a field has been set.
func (o *QuoteTermView) HasAgreementStartDateDefault() bool {
	if o != nil && !IsNil(o.AgreementStartDateDefault) {
		return true
	}

	return false
}

// SetAgreementStartDateDefault gets a reference to the given string and assigns it to the AgreementStartDateDefault field.
func (o *QuoteTermView) SetAgreementStartDateDefault(v string) {
	o.AgreementStartDateDefault = &v
}

func (o QuoteTermView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteTermView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IdQuote) {
		toSerialize["idQuote"] = o.IdQuote
	}
	if !IsNil(o.Periods) {
		toSerialize["periods"] = o.Periods
	}
	if !IsNil(o.InterestRate) {
		toSerialize["interestRate"] = o.InterestRate
	}
	if !IsNil(o.DownPayment) {
		toSerialize["downPayment"] = o.DownPayment
	}
	if !IsNil(o.DiscountAmount) {
		toSerialize["discountAmount"] = o.DiscountAmount
	}
	if !IsNil(o.DiscountPercent) {
		toSerialize["discountPercent"] = o.DiscountPercent
	}
	if !IsNil(o.TotalAmount) {
		toSerialize["totalAmount"] = o.TotalAmount
	}
	if !IsNil(o.Principal) {
		toSerialize["principal"] = o.Principal
	}
	if !IsNil(o.PeriodPaymentAmount) {
		toSerialize["periodPaymentAmount"] = o.PeriodPaymentAmount
	}
	if !IsNil(o.PeriodInterval) {
		toSerialize["periodInterval"] = o.PeriodInterval
	}
	if !IsNil(o.IsSelected) {
		toSerialize["isSelected"] = o.IsSelected
	}
	if !IsNil(o.RecurringDiscountAmount) {
		toSerialize["recurringDiscountAmount"] = o.RecurringDiscountAmount
	}
	if !IsNil(o.RecurringDiscountPercent) {
		toSerialize["recurringDiscountPercent"] = o.RecurringDiscountPercent
	}
	if !IsNil(o.RecurringTotalAmount) {
		toSerialize["recurringTotalAmount"] = o.RecurringTotalAmount
	}
	if !IsNil(o.FinancingGroup) {
		toSerialize["financingGroup"] = o.FinancingGroup
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.RecurringBeforeDiscount) {
		toSerialize["recurringBeforeDiscount"] = o.RecurringBeforeDiscount
	}
	if !IsNil(o.TabGroup) {
		toSerialize["tabGroup"] = o.TabGroup
	}
	if !IsNil(o.GroupSort) {
		toSerialize["groupSort"] = o.GroupSort
	}
	if !IsNil(o.NameSort) {
		toSerialize["nameSort"] = o.NameSort
	}
	if !IsNil(o.TabName) {
		toSerialize["tabName"] = o.TabName
	}
	if !IsNil(o.TotalAmountOverride) {
		toSerialize["totalAmountOverride"] = o.TotalAmountOverride
	}
	if !IsNil(o.RecurringTotalAmountOverride) {
		toSerialize["recurringTotalAmountOverride"] = o.RecurringTotalAmountOverride
	}
	if !IsNil(o.IdRecurringRevenue) {
		toSerialize["idRecurringRevenue"] = o.IdRecurringRevenue
	}
	if !IsNil(o.RecurringPeriods) {
		toSerialize["recurringPeriods"] = o.RecurringPeriods
	}
	if !IsNil(o.RecurringTotalAggregated) {
		toSerialize["recurringTotalAggregated"] = o.RecurringTotalAggregated
	}
	if !IsNil(o.SubscriptionName) {
		toSerialize["subscriptionName"] = o.SubscriptionName
	}
	if !IsNil(o.IsAutomaticallyBillable) {
		toSerialize["isAutomaticallyBillable"] = o.IsAutomaticallyBillable
	}
	if !IsNil(o.OverrideStartDate) {
		toSerialize["overrideStartDate"] = o.OverrideStartDate
	}
	if !IsNil(o.StartDateMode) {
		toSerialize["startDateMode"] = o.StartDateMode
	}
	if !IsNil(o.AuthorizeNetIntervalUnit) {
		toSerialize["authorizeNetIntervalUnit"] = o.AuthorizeNetIntervalUnit
	}
	if !IsNil(o.AuthorizeNetIntervalLength) {
		toSerialize["authorizeNetIntervalLength"] = o.AuthorizeNetIntervalLength
	}
	if !IsNil(o.AuthorizeNetTotalOccurances) {
		toSerialize["authorizeNetTotalOccurances"] = o.AuthorizeNetTotalOccurances
	}
	if !IsNil(o.IntervalToStart) {
		toSerialize["intervalToStart"] = o.IntervalToStart
	}
	if !IsNil(o.OppRecurringAsAdjustment) {
		toSerialize["oppRecurringAsAdjustment"] = o.OppRecurringAsAdjustment
	}
	if !IsNil(o.SpreadOneTime) {
		toSerialize["spreadOneTime"] = o.SpreadOneTime
	}
	if !IsNil(o.IsPrinted) {
		toSerialize["isPrinted"] = o.IsPrinted
	}
	if !IsNil(o.RecurringRevenueLabel) {
		toSerialize["recurringRevenueLabel"] = o.RecurringRevenueLabel
	}
	if !IsNil(o.TabExcludeFilter) {
		toSerialize["tabExcludeFilter"] = o.TabExcludeFilter
	}
	if !IsNil(o.TabIncludeFilter) {
		toSerialize["tabIncludeFilter"] = o.TabIncludeFilter
	}
	if !IsNil(o.IsRoundedPayments) {
		toSerialize["isRoundedPayments"] = o.IsRoundedPayments
	}
	if !IsNil(o.ObeyStandardTabFilters) {
		toSerialize["obeyStandardTabFilters"] = o.ObeyStandardTabFilters
	}
	if !IsNil(o.LeasingName) {
		toSerialize["leasingName"] = o.LeasingName
	}
	if !IsNil(o.LeasingRate) {
		toSerialize["leasingRate"] = o.LeasingRate
	}
	if !IsNil(o.LeasingRateOverride) {
		toSerialize["leasingRateOverride"] = o.LeasingRateOverride
	}
	if !IsNil(o.IsLease) {
		toSerialize["isLease"] = o.IsLease
	}
	if !IsNil(o.LeaseMonthlyAmount) {
		toSerialize["leaseMonthlyAmount"] = o.LeaseMonthlyAmount
	}
	if !IsNil(o.LeaseDownPayment) {
		toSerialize["leaseDownPayment"] = o.LeaseDownPayment
	}
	if !IsNil(o.IdLeasingRates) {
		toSerialize["idLeasingRates"] = o.IdLeasingRates
	}
	if !IsNil(o.LeaseSource) {
		toSerialize["leaseSource"] = o.LeaseSource
	}
	if !IsNil(o.LeaseType) {
		toSerialize["leaseType"] = o.LeaseType
	}
	if !IsNil(o.LeaseTypeDescription) {
		toSerialize["leaseTypeDescription"] = o.LeaseTypeDescription
	}
	if !IsNil(o.LeaseRateCardNumber) {
		toSerialize["leaseRateCardNumber"] = o.LeaseRateCardNumber
	}
	if !IsNil(o.ForceIncludeInForecast) {
		toSerialize["forceIncludeInForecast"] = o.ForceIncludeInForecast
	}
	if !IsNil(o.ForceExcludeInForecast) {
		toSerialize["forceExcludeInForecast"] = o.ForceExcludeInForecast
	}
	if !IsNil(o.Cost) {
		toSerialize["cost"] = o.Cost
	}
	if !IsNil(o.RecurringCost) {
		toSerialize["recurringCost"] = o.RecurringCost
	}
	if !IsNil(o.AgreementType) {
		toSerialize["agreementType"] = o.AgreementType
	}
	if !IsNil(o.AgreementStartDateDefault) {
		toSerialize["agreementStartDateDefault"] = o.AgreementStartDateDefault
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QuoteTermView) UnmarshalJSON(data []byte) (err error) {
	varQuoteTermView := _QuoteTermView{}

	err = json.Unmarshal(data, &varQuoteTermView)

	if err != nil {
		return err
	}

	*o = QuoteTermView(varQuoteTermView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "idQuote")
		delete(additionalProperties, "periods")
		delete(additionalProperties, "interestRate")
		delete(additionalProperties, "downPayment")
		delete(additionalProperties, "discountAmount")
		delete(additionalProperties, "discountPercent")
		delete(additionalProperties, "totalAmount")
		delete(additionalProperties, "principal")
		delete(additionalProperties, "periodPaymentAmount")
		delete(additionalProperties, "periodInterval")
		delete(additionalProperties, "isSelected")
		delete(additionalProperties, "recurringDiscountAmount")
		delete(additionalProperties, "recurringDiscountPercent")
		delete(additionalProperties, "recurringTotalAmount")
		delete(additionalProperties, "financingGroup")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "recurringBeforeDiscount")
		delete(additionalProperties, "tabGroup")
		delete(additionalProperties, "groupSort")
		delete(additionalProperties, "nameSort")
		delete(additionalProperties, "tabName")
		delete(additionalProperties, "totalAmountOverride")
		delete(additionalProperties, "recurringTotalAmountOverride")
		delete(additionalProperties, "idRecurringRevenue")
		delete(additionalProperties, "recurringPeriods")
		delete(additionalProperties, "recurringTotalAggregated")
		delete(additionalProperties, "subscriptionName")
		delete(additionalProperties, "isAutomaticallyBillable")
		delete(additionalProperties, "overrideStartDate")
		delete(additionalProperties, "startDateMode")
		delete(additionalProperties, "authorizeNetIntervalUnit")
		delete(additionalProperties, "authorizeNetIntervalLength")
		delete(additionalProperties, "authorizeNetTotalOccurances")
		delete(additionalProperties, "intervalToStart")
		delete(additionalProperties, "oppRecurringAsAdjustment")
		delete(additionalProperties, "spreadOneTime")
		delete(additionalProperties, "isPrinted")
		delete(additionalProperties, "recurringRevenueLabel")
		delete(additionalProperties, "tabExcludeFilter")
		delete(additionalProperties, "tabIncludeFilter")
		delete(additionalProperties, "isRoundedPayments")
		delete(additionalProperties, "obeyStandardTabFilters")
		delete(additionalProperties, "leasingName")
		delete(additionalProperties, "leasingRate")
		delete(additionalProperties, "leasingRateOverride")
		delete(additionalProperties, "isLease")
		delete(additionalProperties, "leaseMonthlyAmount")
		delete(additionalProperties, "leaseDownPayment")
		delete(additionalProperties, "idLeasingRates")
		delete(additionalProperties, "leaseSource")
		delete(additionalProperties, "leaseType")
		delete(additionalProperties, "leaseTypeDescription")
		delete(additionalProperties, "leaseRateCardNumber")
		delete(additionalProperties, "forceIncludeInForecast")
		delete(additionalProperties, "forceExcludeInForecast")
		delete(additionalProperties, "cost")
		delete(additionalProperties, "recurringCost")
		delete(additionalProperties, "agreementType")
		delete(additionalProperties, "agreementStartDateDefault")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQuoteTermView struct {
	value *QuoteTermView
	isSet bool
}

func (v NullableQuoteTermView) Get() *QuoteTermView {
	return v.value
}

func (v *NullableQuoteTermView) Set(val *QuoteTermView) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteTermView) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteTermView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteTermView(val *QuoteTermView) *NullableQuoteTermView {
	return &NullableQuoteTermView{value: val, isSet: true}
}

func (v NullableQuoteTermView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteTermView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
