/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
)

// checks if the TaxCodeView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaxCodeView{}

// TaxCodeView struct for TaxCodeView
type TaxCodeView struct {
	// This field is Read Only.
	Id                     *string  `json:"id,omitempty"`
	TaxCode                *string  `json:"taxCode,omitempty"`
	TaxRate                *float64 `json:"taxRate,omitempty"`
	GstRate                *float64 `json:"gstRate,omitempty"`
	PstRate                *float64 `json:"pstRate,omitempty"`
	TaxExternalXref        *string  `json:"taxExternalXref,omitempty"`
	IsCalculatedExternally *bool    `json:"isCalculatedExternally,omitempty"`
	AdditionalProperties   map[string]interface{}
}

type _TaxCodeView TaxCodeView

// NewTaxCodeView instantiates a new TaxCodeView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaxCodeView() *TaxCodeView {
	this := TaxCodeView{}
	return &this
}

// NewTaxCodeViewWithDefaults instantiates a new TaxCodeView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaxCodeViewWithDefaults() *TaxCodeView {
	this := TaxCodeView{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TaxCodeView) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxCodeView) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TaxCodeView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TaxCodeView) SetId(v string) {
	o.Id = &v
}

// GetTaxCode returns the TaxCode field value if set, zero value otherwise.
func (o *TaxCodeView) GetTaxCode() string {
	if o == nil || IsNil(o.TaxCode) {
		var ret string
		return ret
	}
	return *o.TaxCode
}

// GetTaxCodeOk returns a tuple with the TaxCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxCodeView) GetTaxCodeOk() (*string, bool) {
	if o == nil || IsNil(o.TaxCode) {
		return nil, false
	}
	return o.TaxCode, true
}

// HasTaxCode returns a boolean if a field has been set.
func (o *TaxCodeView) HasTaxCode() bool {
	if o != nil && !IsNil(o.TaxCode) {
		return true
	}

	return false
}

// SetTaxCode gets a reference to the given string and assigns it to the TaxCode field.
func (o *TaxCodeView) SetTaxCode(v string) {
	o.TaxCode = &v
}

// GetTaxRate returns the TaxRate field value if set, zero value otherwise.
func (o *TaxCodeView) GetTaxRate() float64 {
	if o == nil || IsNil(o.TaxRate) {
		var ret float64
		return ret
	}
	return *o.TaxRate
}

// GetTaxRateOk returns a tuple with the TaxRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxCodeView) GetTaxRateOk() (*float64, bool) {
	if o == nil || IsNil(o.TaxRate) {
		return nil, false
	}
	return o.TaxRate, true
}

// HasTaxRate returns a boolean if a field has been set.
func (o *TaxCodeView) HasTaxRate() bool {
	if o != nil && !IsNil(o.TaxRate) {
		return true
	}

	return false
}

// SetTaxRate gets a reference to the given float64 and assigns it to the TaxRate field.
func (o *TaxCodeView) SetTaxRate(v float64) {
	o.TaxRate = &v
}

// GetGstRate returns the GstRate field value if set, zero value otherwise.
func (o *TaxCodeView) GetGstRate() float64 {
	if o == nil || IsNil(o.GstRate) {
		var ret float64
		return ret
	}
	return *o.GstRate
}

// GetGstRateOk returns a tuple with the GstRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxCodeView) GetGstRateOk() (*float64, bool) {
	if o == nil || IsNil(o.GstRate) {
		return nil, false
	}
	return o.GstRate, true
}

// HasGstRate returns a boolean if a field has been set.
func (o *TaxCodeView) HasGstRate() bool {
	if o != nil && !IsNil(o.GstRate) {
		return true
	}

	return false
}

// SetGstRate gets a reference to the given float64 and assigns it to the GstRate field.
func (o *TaxCodeView) SetGstRate(v float64) {
	o.GstRate = &v
}

// GetPstRate returns the PstRate field value if set, zero value otherwise.
func (o *TaxCodeView) GetPstRate() float64 {
	if o == nil || IsNil(o.PstRate) {
		var ret float64
		return ret
	}
	return *o.PstRate
}

// GetPstRateOk returns a tuple with the PstRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxCodeView) GetPstRateOk() (*float64, bool) {
	if o == nil || IsNil(o.PstRate) {
		return nil, false
	}
	return o.PstRate, true
}

// HasPstRate returns a boolean if a field has been set.
func (o *TaxCodeView) HasPstRate() bool {
	if o != nil && !IsNil(o.PstRate) {
		return true
	}

	return false
}

// SetPstRate gets a reference to the given float64 and assigns it to the PstRate field.
func (o *TaxCodeView) SetPstRate(v float64) {
	o.PstRate = &v
}

// GetTaxExternalXref returns the TaxExternalXref field value if set, zero value otherwise.
func (o *TaxCodeView) GetTaxExternalXref() string {
	if o == nil || IsNil(o.TaxExternalXref) {
		var ret string
		return ret
	}
	return *o.TaxExternalXref
}

// GetTaxExternalXrefOk returns a tuple with the TaxExternalXref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxCodeView) GetTaxExternalXrefOk() (*string, bool) {
	if o == nil || IsNil(o.TaxExternalXref) {
		return nil, false
	}
	return o.TaxExternalXref, true
}

// HasTaxExternalXref returns a boolean if a field has been set.
func (o *TaxCodeView) HasTaxExternalXref() bool {
	if o != nil && !IsNil(o.TaxExternalXref) {
		return true
	}

	return false
}

// SetTaxExternalXref gets a reference to the given string and assigns it to the TaxExternalXref field.
func (o *TaxCodeView) SetTaxExternalXref(v string) {
	o.TaxExternalXref = &v
}

// GetIsCalculatedExternally returns the IsCalculatedExternally field value if set, zero value otherwise.
func (o *TaxCodeView) GetIsCalculatedExternally() bool {
	if o == nil || IsNil(o.IsCalculatedExternally) {
		var ret bool
		return ret
	}
	return *o.IsCalculatedExternally
}

// GetIsCalculatedExternallyOk returns a tuple with the IsCalculatedExternally field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxCodeView) GetIsCalculatedExternallyOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCalculatedExternally) {
		return nil, false
	}
	return o.IsCalculatedExternally, true
}

// HasIsCalculatedExternally returns a boolean if a field has been set.
func (o *TaxCodeView) HasIsCalculatedExternally() bool {
	if o != nil && !IsNil(o.IsCalculatedExternally) {
		return true
	}

	return false
}

// SetIsCalculatedExternally gets a reference to the given bool and assigns it to the IsCalculatedExternally field.
func (o *TaxCodeView) SetIsCalculatedExternally(v bool) {
	o.IsCalculatedExternally = &v
}

func (o TaxCodeView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaxCodeView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.TaxCode) {
		toSerialize["taxCode"] = o.TaxCode
	}
	if !IsNil(o.TaxRate) {
		toSerialize["taxRate"] = o.TaxRate
	}
	if !IsNil(o.GstRate) {
		toSerialize["gstRate"] = o.GstRate
	}
	if !IsNil(o.PstRate) {
		toSerialize["pstRate"] = o.PstRate
	}
	if !IsNil(o.TaxExternalXref) {
		toSerialize["taxExternalXref"] = o.TaxExternalXref
	}
	if !IsNil(o.IsCalculatedExternally) {
		toSerialize["isCalculatedExternally"] = o.IsCalculatedExternally
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TaxCodeView) UnmarshalJSON(data []byte) (err error) {
	varTaxCodeView := _TaxCodeView{}

	err = json.Unmarshal(data, &varTaxCodeView)

	if err != nil {
		return err
	}

	*o = TaxCodeView(varTaxCodeView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "taxCode")
		delete(additionalProperties, "taxRate")
		delete(additionalProperties, "gstRate")
		delete(additionalProperties, "pstRate")
		delete(additionalProperties, "taxExternalXref")
		delete(additionalProperties, "isCalculatedExternally")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTaxCodeView struct {
	value *TaxCodeView
	isSet bool
}

func (v NullableTaxCodeView) Get() *TaxCodeView {
	return v.value
}

func (v *NullableTaxCodeView) Set(val *TaxCodeView) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxCodeView) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxCodeView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxCodeView(val *TaxCodeView) *NullableTaxCodeView {
	return &NullableTaxCodeView{value: val, isSet: true}
}

func (v NullableTaxCodeView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxCodeView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
