/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
)

// checks if the OperationQuoteView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationQuoteView{}

// OperationQuoteView struct for OperationQuoteView
type OperationQuoteView struct {
	Value                map[string]interface{} `json:"value,omitempty"`
	Path                 *string                `json:"path,omitempty"`
	Op                   *string                `json:"op,omitempty"`
	From                 *string                `json:"from,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OperationQuoteView OperationQuoteView

// NewOperationQuoteView instantiates a new OperationQuoteView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationQuoteView() *OperationQuoteView {
	this := OperationQuoteView{}
	return &this
}

// NewOperationQuoteViewWithDefaults instantiates a new OperationQuoteView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationQuoteViewWithDefaults() *OperationQuoteView {
	this := OperationQuoteView{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *OperationQuoteView) GetValue() map[string]interface{} {
	if o == nil || IsNil(o.Value) {
		var ret map[string]interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationQuoteView) GetValueOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return map[string]interface{}{}, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *OperationQuoteView) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]interface{} and assigns it to the Value field.
func (o *OperationQuoteView) SetValue(v map[string]interface{}) {
	o.Value = v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *OperationQuoteView) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationQuoteView) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *OperationQuoteView) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *OperationQuoteView) SetPath(v string) {
	o.Path = &v
}

// GetOp returns the Op field value if set, zero value otherwise.
func (o *OperationQuoteView) GetOp() string {
	if o == nil || IsNil(o.Op) {
		var ret string
		return ret
	}
	return *o.Op
}

// GetOpOk returns a tuple with the Op field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationQuoteView) GetOpOk() (*string, bool) {
	if o == nil || IsNil(o.Op) {
		return nil, false
	}
	return o.Op, true
}

// HasOp returns a boolean if a field has been set.
func (o *OperationQuoteView) HasOp() bool {
	if o != nil && !IsNil(o.Op) {
		return true
	}

	return false
}

// SetOp gets a reference to the given string and assigns it to the Op field.
func (o *OperationQuoteView) SetOp(v string) {
	o.Op = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *OperationQuoteView) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationQuoteView) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *OperationQuoteView) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *OperationQuoteView) SetFrom(v string) {
	o.From = &v
}

func (o OperationQuoteView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationQuoteView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Op) {
		toSerialize["op"] = o.Op
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OperationQuoteView) UnmarshalJSON(data []byte) (err error) {
	varOperationQuoteView := _OperationQuoteView{}

	err = json.Unmarshal(data, &varOperationQuoteView)

	if err != nil {
		return err
	}

	*o = OperationQuoteView(varOperationQuoteView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "path")
		delete(additionalProperties, "op")
		delete(additionalProperties, "from")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOperationQuoteView struct {
	value *OperationQuoteView
	isSet bool
}

func (v NullableOperationQuoteView) Get() *OperationQuoteView {
	return v.value
}

func (v *NullableOperationQuoteView) Set(val *OperationQuoteView) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationQuoteView) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationQuoteView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationQuoteView(val *OperationQuoteView) *NullableOperationQuoteView {
	return &NullableOperationQuoteView{value: val, isSet: true}
}

func (v NullableOperationQuoteView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationQuoteView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
