/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
)

// checks if the QuoteQueryModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteQueryModel{}

// QuoteQueryModel struct for QuoteQueryModel
type QuoteQueryModel struct {
	// Set true for results from deleted or archived quotes. Defaults to false.
	ShowAllVersions *bool `json:"showAllVersions,omitempty"`
	// Comma separated list of fields to return.
	IncludeFields *string `json:"includeFields,omitempty"`
	// Conditional retrieve statements.
	Conditions *string `json:"conditions,omitempty"`
	// Page of results to get. 1-index based.
	Page *int32 `json:"page,omitempty"`
	// Page size of results to get. Max size 1000, default 50.
	PageSize             *int32 `json:"pageSize,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _QuoteQueryModel QuoteQueryModel

// NewQuoteQueryModel instantiates a new QuoteQueryModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteQueryModel() *QuoteQueryModel {
	this := QuoteQueryModel{}
	return &this
}

// NewQuoteQueryModelWithDefaults instantiates a new QuoteQueryModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteQueryModelWithDefaults() *QuoteQueryModel {
	this := QuoteQueryModel{}
	return &this
}

// GetShowAllVersions returns the ShowAllVersions field value if set, zero value otherwise.
func (o *QuoteQueryModel) GetShowAllVersions() bool {
	if o == nil || IsNil(o.ShowAllVersions) {
		var ret bool
		return ret
	}
	return *o.ShowAllVersions
}

// GetShowAllVersionsOk returns a tuple with the ShowAllVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteQueryModel) GetShowAllVersionsOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowAllVersions) {
		return nil, false
	}
	return o.ShowAllVersions, true
}

// HasShowAllVersions returns a boolean if a field has been set.
func (o *QuoteQueryModel) HasShowAllVersions() bool {
	if o != nil && !IsNil(o.ShowAllVersions) {
		return true
	}

	return false
}

// SetShowAllVersions gets a reference to the given bool and assigns it to the ShowAllVersions field.
func (o *QuoteQueryModel) SetShowAllVersions(v bool) {
	o.ShowAllVersions = &v
}

// GetIncludeFields returns the IncludeFields field value if set, zero value otherwise.
func (o *QuoteQueryModel) GetIncludeFields() string {
	if o == nil || IsNil(o.IncludeFields) {
		var ret string
		return ret
	}
	return *o.IncludeFields
}

// GetIncludeFieldsOk returns a tuple with the IncludeFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteQueryModel) GetIncludeFieldsOk() (*string, bool) {
	if o == nil || IsNil(o.IncludeFields) {
		return nil, false
	}
	return o.IncludeFields, true
}

// HasIncludeFields returns a boolean if a field has been set.
func (o *QuoteQueryModel) HasIncludeFields() bool {
	if o != nil && !IsNil(o.IncludeFields) {
		return true
	}

	return false
}

// SetIncludeFields gets a reference to the given string and assigns it to the IncludeFields field.
func (o *QuoteQueryModel) SetIncludeFields(v string) {
	o.IncludeFields = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *QuoteQueryModel) GetConditions() string {
	if o == nil || IsNil(o.Conditions) {
		var ret string
		return ret
	}
	return *o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteQueryModel) GetConditionsOk() (*string, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *QuoteQueryModel) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given string and assigns it to the Conditions field.
func (o *QuoteQueryModel) SetConditions(v string) {
	o.Conditions = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *QuoteQueryModel) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteQueryModel) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *QuoteQueryModel) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *QuoteQueryModel) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *QuoteQueryModel) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteQueryModel) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *QuoteQueryModel) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *QuoteQueryModel) SetPageSize(v int32) {
	o.PageSize = &v
}

func (o QuoteQueryModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteQueryModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ShowAllVersions) {
		toSerialize["showAllVersions"] = o.ShowAllVersions
	}
	if !IsNil(o.IncludeFields) {
		toSerialize["includeFields"] = o.IncludeFields
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QuoteQueryModel) UnmarshalJSON(data []byte) (err error) {
	varQuoteQueryModel := _QuoteQueryModel{}

	err = json.Unmarshal(data, &varQuoteQueryModel)

	if err != nil {
		return err
	}

	*o = QuoteQueryModel(varQuoteQueryModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "showAllVersions")
		delete(additionalProperties, "includeFields")
		delete(additionalProperties, "conditions")
		delete(additionalProperties, "page")
		delete(additionalProperties, "pageSize")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQuoteQueryModel struct {
	value *QuoteQueryModel
	isSet bool
}

func (v NullableQuoteQueryModel) Get() *QuoteQueryModel {
	return v.value
}

func (v *NullableQuoteQueryModel) Set(val *QuoteQueryModel) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteQueryModel) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteQueryModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteQueryModel(val *QuoteQueryModel) *NullableQuoteQueryModel {
	return &NullableQuoteQueryModel{value: val, isSet: true}
}

func (v NullableQuoteQueryModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteQueryModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
