/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
)

// checks if the JsonPatchDocumentUserView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JsonPatchDocumentUserView{}

// JsonPatchDocumentUserView struct for JsonPatchDocumentUserView
type JsonPatchDocumentUserView struct {
	// This field is Read Only.
	Operations           []OperationUserView `json:"operations,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JsonPatchDocumentUserView JsonPatchDocumentUserView

// NewJsonPatchDocumentUserView instantiates a new JsonPatchDocumentUserView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJsonPatchDocumentUserView() *JsonPatchDocumentUserView {
	this := JsonPatchDocumentUserView{}
	return &this
}

// NewJsonPatchDocumentUserViewWithDefaults instantiates a new JsonPatchDocumentUserView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJsonPatchDocumentUserViewWithDefaults() *JsonPatchDocumentUserView {
	this := JsonPatchDocumentUserView{}
	return &this
}

// GetOperations returns the Operations field value if set, zero value otherwise.
func (o *JsonPatchDocumentUserView) GetOperations() []OperationUserView {
	if o == nil || IsNil(o.Operations) {
		var ret []OperationUserView
		return ret
	}
	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JsonPatchDocumentUserView) GetOperationsOk() ([]OperationUserView, bool) {
	if o == nil || IsNil(o.Operations) {
		return nil, false
	}
	return o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *JsonPatchDocumentUserView) HasOperations() bool {
	if o != nil && !IsNil(o.Operations) {
		return true
	}

	return false
}

// SetOperations gets a reference to the given []OperationUserView and assigns it to the Operations field.
func (o *JsonPatchDocumentUserView) SetOperations(v []OperationUserView) {
	o.Operations = v
}

func (o JsonPatchDocumentUserView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JsonPatchDocumentUserView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Operations) {
		toSerialize["operations"] = o.Operations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JsonPatchDocumentUserView) UnmarshalJSON(data []byte) (err error) {
	varJsonPatchDocumentUserView := _JsonPatchDocumentUserView{}

	err = json.Unmarshal(data, &varJsonPatchDocumentUserView)

	if err != nil {
		return err
	}

	*o = JsonPatchDocumentUserView(varJsonPatchDocumentUserView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "operations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJsonPatchDocumentUserView struct {
	value *JsonPatchDocumentUserView
	isSet bool
}

func (v NullableJsonPatchDocumentUserView) Get() *JsonPatchDocumentUserView {
	return v.value
}

func (v *NullableJsonPatchDocumentUserView) Set(val *JsonPatchDocumentUserView) {
	v.value = val
	v.isSet = true
}

func (v NullableJsonPatchDocumentUserView) IsSet() bool {
	return v.isSet
}

func (v *NullableJsonPatchDocumentUserView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJsonPatchDocumentUserView(val *JsonPatchDocumentUserView) *NullableJsonPatchDocumentUserView {
	return &NullableJsonPatchDocumentUserView{value: val, isSet: true}
}

func (v NullableJsonPatchDocumentUserView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJsonPatchDocumentUserView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
