/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
)

// checks if the OperationQuoteItemView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationQuoteItemView{}

// OperationQuoteItemView struct for OperationQuoteItemView
type OperationQuoteItemView struct {
	Value                map[string]interface{} `json:"value,omitempty"`
	Path                 *string                `json:"path,omitempty"`
	Op                   *string                `json:"op,omitempty"`
	From                 *string                `json:"from,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OperationQuoteItemView OperationQuoteItemView

// NewOperationQuoteItemView instantiates a new OperationQuoteItemView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationQuoteItemView() *OperationQuoteItemView {
	this := OperationQuoteItemView{}
	return &this
}

// NewOperationQuoteItemViewWithDefaults instantiates a new OperationQuoteItemView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationQuoteItemViewWithDefaults() *OperationQuoteItemView {
	this := OperationQuoteItemView{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *OperationQuoteItemView) GetValue() map[string]interface{} {
	if o == nil || IsNil(o.Value) {
		var ret map[string]interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationQuoteItemView) GetValueOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return map[string]interface{}{}, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *OperationQuoteItemView) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]interface{} and assigns it to the Value field.
func (o *OperationQuoteItemView) SetValue(v map[string]interface{}) {
	o.Value = v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *OperationQuoteItemView) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationQuoteItemView) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *OperationQuoteItemView) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *OperationQuoteItemView) SetPath(v string) {
	o.Path = &v
}

// GetOp returns the Op field value if set, zero value otherwise.
func (o *OperationQuoteItemView) GetOp() string {
	if o == nil || IsNil(o.Op) {
		var ret string
		return ret
	}
	return *o.Op
}

// GetOpOk returns a tuple with the Op field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationQuoteItemView) GetOpOk() (*string, bool) {
	if o == nil || IsNil(o.Op) {
		return nil, false
	}
	return o.Op, true
}

// HasOp returns a boolean if a field has been set.
func (o *OperationQuoteItemView) HasOp() bool {
	if o != nil && !IsNil(o.Op) {
		return true
	}

	return false
}

// SetOp gets a reference to the given string and assigns it to the Op field.
func (o *OperationQuoteItemView) SetOp(v string) {
	o.Op = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *OperationQuoteItemView) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationQuoteItemView) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *OperationQuoteItemView) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *OperationQuoteItemView) SetFrom(v string) {
	o.From = &v
}

func (o OperationQuoteItemView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationQuoteItemView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Op) {
		toSerialize["op"] = o.Op
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OperationQuoteItemView) UnmarshalJSON(data []byte) (err error) {
	varOperationQuoteItemView := _OperationQuoteItemView{}

	err = json.Unmarshal(data, &varOperationQuoteItemView)

	if err != nil {
		return err
	}

	*o = OperationQuoteItemView(varOperationQuoteItemView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "path")
		delete(additionalProperties, "op")
		delete(additionalProperties, "from")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOperationQuoteItemView struct {
	value *OperationQuoteItemView
	isSet bool
}

func (v NullableOperationQuoteItemView) Get() *OperationQuoteItemView {
	return v.value
}

func (v *NullableOperationQuoteItemView) Set(val *OperationQuoteItemView) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationQuoteItemView) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationQuoteItemView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationQuoteItemView(val *OperationQuoteItemView) *NullableOperationQuoteItemView {
	return &NullableOperationQuoteItemView{value: val, isSet: true}
}

func (v NullableOperationQuoteItemView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationQuoteItemView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
