/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
)

// checks if the ReferenceLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferenceLink{}

// ReferenceLink struct for ReferenceLink
type ReferenceLink struct {
	Id                   *string            `json:"id,omitempty"`
	Name                 *string            `json:"name,omitempty"`
	Info                 *map[string]string `json:"_info,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReferenceLink ReferenceLink

// NewReferenceLink instantiates a new ReferenceLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferenceLink() *ReferenceLink {
	this := ReferenceLink{}
	return &this
}

// NewReferenceLinkWithDefaults instantiates a new ReferenceLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferenceLinkWithDefaults() *ReferenceLink {
	this := ReferenceLink{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ReferenceLink) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferenceLink) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ReferenceLink) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ReferenceLink) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ReferenceLink) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferenceLink) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ReferenceLink) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ReferenceLink) SetName(v string) {
	o.Name = &v
}

// GetInfo returns the Info field value if set, zero value otherwise.
func (o *ReferenceLink) GetInfo() map[string]string {
	if o == nil || IsNil(o.Info) {
		var ret map[string]string
		return ret
	}
	return *o.Info
}

// GetInfoOk returns a tuple with the Info field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferenceLink) GetInfoOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Info) {
		return nil, false
	}
	return o.Info, true
}

// HasInfo returns a boolean if a field has been set.
func (o *ReferenceLink) HasInfo() bool {
	if o != nil && !IsNil(o.Info) {
		return true
	}

	return false
}

// SetInfo gets a reference to the given map[string]string and assigns it to the Info field.
func (o *ReferenceLink) SetInfo(v map[string]string) {
	o.Info = &v
}

func (o ReferenceLink) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferenceLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Info) {
		toSerialize["_info"] = o.Info
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReferenceLink) UnmarshalJSON(data []byte) (err error) {
	varReferenceLink := _ReferenceLink{}

	err = json.Unmarshal(data, &varReferenceLink)

	if err != nil {
		return err
	}

	*o = ReferenceLink(varReferenceLink)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "_info")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReferenceLink struct {
	value *ReferenceLink
	isSet bool
}

func (v NullableReferenceLink) Get() *ReferenceLink {
	return v.value
}

func (v *NullableReferenceLink) Set(val *ReferenceLink) {
	v.value = val
	v.isSet = true
}

func (v NullableReferenceLink) IsSet() bool {
	return v.isSet
}

func (v *NullableReferenceLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferenceLink(val *ReferenceLink) *NullableReferenceLink {
	return &NullableReferenceLink{value: val, isSet: true}
}

func (v NullableReferenceLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferenceLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
