/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
)

// checks if the JsonPatchDocumentQuoteItemView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JsonPatchDocumentQuoteItemView{}

// JsonPatchDocumentQuoteItemView struct for JsonPatchDocumentQuoteItemView
type JsonPatchDocumentQuoteItemView struct {
	// This field is Read Only.
	Operations           []OperationQuoteItemView `json:"operations,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JsonPatchDocumentQuoteItemView JsonPatchDocumentQuoteItemView

// NewJsonPatchDocumentQuoteItemView instantiates a new JsonPatchDocumentQuoteItemView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJsonPatchDocumentQuoteItemView() *JsonPatchDocumentQuoteItemView {
	this := JsonPatchDocumentQuoteItemView{}
	return &this
}

// NewJsonPatchDocumentQuoteItemViewWithDefaults instantiates a new JsonPatchDocumentQuoteItemView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJsonPatchDocumentQuoteItemViewWithDefaults() *JsonPatchDocumentQuoteItemView {
	this := JsonPatchDocumentQuoteItemView{}
	return &this
}

// GetOperations returns the Operations field value if set, zero value otherwise.
func (o *JsonPatchDocumentQuoteItemView) GetOperations() []OperationQuoteItemView {
	if o == nil || IsNil(o.Operations) {
		var ret []OperationQuoteItemView
		return ret
	}
	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JsonPatchDocumentQuoteItemView) GetOperationsOk() ([]OperationQuoteItemView, bool) {
	if o == nil || IsNil(o.Operations) {
		return nil, false
	}
	return o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *JsonPatchDocumentQuoteItemView) HasOperations() bool {
	if o != nil && !IsNil(o.Operations) {
		return true
	}

	return false
}

// SetOperations gets a reference to the given []OperationQuoteItemView and assigns it to the Operations field.
func (o *JsonPatchDocumentQuoteItemView) SetOperations(v []OperationQuoteItemView) {
	o.Operations = v
}

func (o JsonPatchDocumentQuoteItemView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JsonPatchDocumentQuoteItemView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Operations) {
		toSerialize["operations"] = o.Operations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JsonPatchDocumentQuoteItemView) UnmarshalJSON(data []byte) (err error) {
	varJsonPatchDocumentQuoteItemView := _JsonPatchDocumentQuoteItemView{}

	err = json.Unmarshal(data, &varJsonPatchDocumentQuoteItemView)

	if err != nil {
		return err
	}

	*o = JsonPatchDocumentQuoteItemView(varJsonPatchDocumentQuoteItemView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "operations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJsonPatchDocumentQuoteItemView struct {
	value *JsonPatchDocumentQuoteItemView
	isSet bool
}

func (v NullableJsonPatchDocumentQuoteItemView) Get() *JsonPatchDocumentQuoteItemView {
	return v.value
}

func (v *NullableJsonPatchDocumentQuoteItemView) Set(val *JsonPatchDocumentQuoteItemView) {
	v.value = val
	v.isSet = true
}

func (v NullableJsonPatchDocumentQuoteItemView) IsSet() bool {
	return v.isSet
}

func (v *NullableJsonPatchDocumentQuoteItemView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJsonPatchDocumentQuoteItemView(val *JsonPatchDocumentQuoteItemView) *NullableJsonPatchDocumentQuoteItemView {
	return &NullableJsonPatchDocumentQuoteItemView{value: val, isSet: true}
}

func (v NullableJsonPatchDocumentQuoteItemView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJsonPatchDocumentQuoteItemView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
