/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
)

// checks if the UserView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserView{}

// UserView struct for UserView
type UserView struct {
	// This field is Read Only.
	Id *string `json:"id,omitempty"`
	// This field is Read Only.
	IsInactiveUser *bool `json:"isInactiveUser,omitempty"`
	// This field is Read Only.
	IsReadOnlyUser *bool `json:"isReadOnlyUser,omitempty"`
	// This field is Read Only.
	FailedLoginCount *int32 `json:"failedLoginCount,omitempty"`
	// This field is Read Only.
	IsApprover *bool `json:"isApprover,omitempty"`
	// This field is Read Only.
	IsPriceChanger *bool `json:"isPriceChanger,omitempty"`
	// This field is Read Only.
	CanAccessAllQuotes *bool `json:"canAccessAllQuotes,omitempty"`
	// This field is Read Only.
	IsAdministrator *bool `json:"isAdministrator,omitempty"`
	// This field is Read Only.
	IsDeveloper *bool `json:"isDeveloper,omitempty"`
	// This field is Read Only.
	IsApiUser *bool `json:"isApiUser,omitempty"`
	// This field is Read Only.
	IsContentManager *bool `json:"isContentManager,omitempty"`
	// This field is Read Only.
	IsStandardPlus *bool `json:"isStandardPlus,omitempty"`
	// This field is Read Only.
	AlwaysRequireManagerApproval *bool `json:"alwaysRequireManagerApproval,omitempty"`
	// This field is Read Only.
	IsPublisher *bool `json:"isPublisher,omitempty"`
	// This field is Read Only.
	IsManualWinner *bool `json:"isManualWinner,omitempty"`
	// This field is Read Only.
	ElectronicOrderUser *bool `json:"electronicOrderUser,omitempty"`
	// This field is Read Only.
	IdProfileTeams *string `json:"idProfileTeams,omitempty"`
	LocationId     *string `json:"locationId,omitempty"`
	// This field is Read Only.
	ManagerUserId *string `json:"managerUserId,omitempty"`
	// This field is Read Only.
	ApproverUserId *string `json:"approverUserId,omitempty"`
	// This field is Read Only.
	UserName      *string `json:"userName,omitempty"`
	FirstName     *string `json:"firstName,omitempty"`
	LastName      *string `json:"lastName,omitempty"`
	PresentedName *string `json:"presentedName,omitempty"`
	JobTitle      *string `json:"jobTitle,omitempty"`
	QuotePreface  *string `json:"quotePreface,omitempty"`
	UserNotes     *string `json:"userNotes,omitempty"`
	// This field is Read Only.
	BaseCurrency              *string `json:"baseCurrency,omitempty"`
	PhoneNumber               *string `json:"phoneNumber,omitempty"`
	MobilePhoneNumber         *string `json:"mobilePhoneNumber,omitempty"`
	EmailAddress              *string `json:"emailAddress,omitempty"`
	MessengerId               *string `json:"messengerId,omitempty"`
	InvoiceRepId              *string `json:"invoiceRepId,omitempty"`
	TimeZone                  *string `json:"timeZone,omitempty"`
	OrderPorterEmailAddresses *string `json:"orderPorterEmailAddresses,omitempty"`
	OnBehalfUser              *string `json:"onBehalfUser,omitempty"`
	DefaultSearchQuoteStatus  *string `json:"defaultSearchQuoteStatus,omitempty"`
	BccEmailAddresses         *string `json:"bccEmailAddresses,omitempty"`
	// This field is Read Only.
	OauthSubscriberId    *string `json:"oauthSubscriberId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UserView UserView

// NewUserView instantiates a new UserView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserView() *UserView {
	this := UserView{}
	return &this
}

// NewUserViewWithDefaults instantiates a new UserView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserViewWithDefaults() *UserView {
	this := UserView{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserView) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UserView) SetId(v string) {
	o.Id = &v
}

// GetIsInactiveUser returns the IsInactiveUser field value if set, zero value otherwise.
func (o *UserView) GetIsInactiveUser() bool {
	if o == nil || IsNil(o.IsInactiveUser) {
		var ret bool
		return ret
	}
	return *o.IsInactiveUser
}

// GetIsInactiveUserOk returns a tuple with the IsInactiveUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIsInactiveUserOk() (*bool, bool) {
	if o == nil || IsNil(o.IsInactiveUser) {
		return nil, false
	}
	return o.IsInactiveUser, true
}

// HasIsInactiveUser returns a boolean if a field has been set.
func (o *UserView) HasIsInactiveUser() bool {
	if o != nil && !IsNil(o.IsInactiveUser) {
		return true
	}

	return false
}

// SetIsInactiveUser gets a reference to the given bool and assigns it to the IsInactiveUser field.
func (o *UserView) SetIsInactiveUser(v bool) {
	o.IsInactiveUser = &v
}

// GetIsReadOnlyUser returns the IsReadOnlyUser field value if set, zero value otherwise.
func (o *UserView) GetIsReadOnlyUser() bool {
	if o == nil || IsNil(o.IsReadOnlyUser) {
		var ret bool
		return ret
	}
	return *o.IsReadOnlyUser
}

// GetIsReadOnlyUserOk returns a tuple with the IsReadOnlyUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIsReadOnlyUserOk() (*bool, bool) {
	if o == nil || IsNil(o.IsReadOnlyUser) {
		return nil, false
	}
	return o.IsReadOnlyUser, true
}

// HasIsReadOnlyUser returns a boolean if a field has been set.
func (o *UserView) HasIsReadOnlyUser() bool {
	if o != nil && !IsNil(o.IsReadOnlyUser) {
		return true
	}

	return false
}

// SetIsReadOnlyUser gets a reference to the given bool and assigns it to the IsReadOnlyUser field.
func (o *UserView) SetIsReadOnlyUser(v bool) {
	o.IsReadOnlyUser = &v
}

// GetFailedLoginCount returns the FailedLoginCount field value if set, zero value otherwise.
func (o *UserView) GetFailedLoginCount() int32 {
	if o == nil || IsNil(o.FailedLoginCount) {
		var ret int32
		return ret
	}
	return *o.FailedLoginCount
}

// GetFailedLoginCountOk returns a tuple with the FailedLoginCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetFailedLoginCountOk() (*int32, bool) {
	if o == nil || IsNil(o.FailedLoginCount) {
		return nil, false
	}
	return o.FailedLoginCount, true
}

// HasFailedLoginCount returns a boolean if a field has been set.
func (o *UserView) HasFailedLoginCount() bool {
	if o != nil && !IsNil(o.FailedLoginCount) {
		return true
	}

	return false
}

// SetFailedLoginCount gets a reference to the given int32 and assigns it to the FailedLoginCount field.
func (o *UserView) SetFailedLoginCount(v int32) {
	o.FailedLoginCount = &v
}

// GetIsApprover returns the IsApprover field value if set, zero value otherwise.
func (o *UserView) GetIsApprover() bool {
	if o == nil || IsNil(o.IsApprover) {
		var ret bool
		return ret
	}
	return *o.IsApprover
}

// GetIsApproverOk returns a tuple with the IsApprover field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIsApproverOk() (*bool, bool) {
	if o == nil || IsNil(o.IsApprover) {
		return nil, false
	}
	return o.IsApprover, true
}

// HasIsApprover returns a boolean if a field has been set.
func (o *UserView) HasIsApprover() bool {
	if o != nil && !IsNil(o.IsApprover) {
		return true
	}

	return false
}

// SetIsApprover gets a reference to the given bool and assigns it to the IsApprover field.
func (o *UserView) SetIsApprover(v bool) {
	o.IsApprover = &v
}

// GetIsPriceChanger returns the IsPriceChanger field value if set, zero value otherwise.
func (o *UserView) GetIsPriceChanger() bool {
	if o == nil || IsNil(o.IsPriceChanger) {
		var ret bool
		return ret
	}
	return *o.IsPriceChanger
}

// GetIsPriceChangerOk returns a tuple with the IsPriceChanger field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIsPriceChangerOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPriceChanger) {
		return nil, false
	}
	return o.IsPriceChanger, true
}

// HasIsPriceChanger returns a boolean if a field has been set.
func (o *UserView) HasIsPriceChanger() bool {
	if o != nil && !IsNil(o.IsPriceChanger) {
		return true
	}

	return false
}

// SetIsPriceChanger gets a reference to the given bool and assigns it to the IsPriceChanger field.
func (o *UserView) SetIsPriceChanger(v bool) {
	o.IsPriceChanger = &v
}

// GetCanAccessAllQuotes returns the CanAccessAllQuotes field value if set, zero value otherwise.
func (o *UserView) GetCanAccessAllQuotes() bool {
	if o == nil || IsNil(o.CanAccessAllQuotes) {
		var ret bool
		return ret
	}
	return *o.CanAccessAllQuotes
}

// GetCanAccessAllQuotesOk returns a tuple with the CanAccessAllQuotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetCanAccessAllQuotesOk() (*bool, bool) {
	if o == nil || IsNil(o.CanAccessAllQuotes) {
		return nil, false
	}
	return o.CanAccessAllQuotes, true
}

// HasCanAccessAllQuotes returns a boolean if a field has been set.
func (o *UserView) HasCanAccessAllQuotes() bool {
	if o != nil && !IsNil(o.CanAccessAllQuotes) {
		return true
	}

	return false
}

// SetCanAccessAllQuotes gets a reference to the given bool and assigns it to the CanAccessAllQuotes field.
func (o *UserView) SetCanAccessAllQuotes(v bool) {
	o.CanAccessAllQuotes = &v
}

// GetIsAdministrator returns the IsAdministrator field value if set, zero value otherwise.
func (o *UserView) GetIsAdministrator() bool {
	if o == nil || IsNil(o.IsAdministrator) {
		var ret bool
		return ret
	}
	return *o.IsAdministrator
}

// GetIsAdministratorOk returns a tuple with the IsAdministrator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIsAdministratorOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAdministrator) {
		return nil, false
	}
	return o.IsAdministrator, true
}

// HasIsAdministrator returns a boolean if a field has been set.
func (o *UserView) HasIsAdministrator() bool {
	if o != nil && !IsNil(o.IsAdministrator) {
		return true
	}

	return false
}

// SetIsAdministrator gets a reference to the given bool and assigns it to the IsAdministrator field.
func (o *UserView) SetIsAdministrator(v bool) {
	o.IsAdministrator = &v
}

// GetIsDeveloper returns the IsDeveloper field value if set, zero value otherwise.
func (o *UserView) GetIsDeveloper() bool {
	if o == nil || IsNil(o.IsDeveloper) {
		var ret bool
		return ret
	}
	return *o.IsDeveloper
}

// GetIsDeveloperOk returns a tuple with the IsDeveloper field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIsDeveloperOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeveloper) {
		return nil, false
	}
	return o.IsDeveloper, true
}

// HasIsDeveloper returns a boolean if a field has been set.
func (o *UserView) HasIsDeveloper() bool {
	if o != nil && !IsNil(o.IsDeveloper) {
		return true
	}

	return false
}

// SetIsDeveloper gets a reference to the given bool and assigns it to the IsDeveloper field.
func (o *UserView) SetIsDeveloper(v bool) {
	o.IsDeveloper = &v
}

// GetIsApiUser returns the IsApiUser field value if set, zero value otherwise.
func (o *UserView) GetIsApiUser() bool {
	if o == nil || IsNil(o.IsApiUser) {
		var ret bool
		return ret
	}
	return *o.IsApiUser
}

// GetIsApiUserOk returns a tuple with the IsApiUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIsApiUserOk() (*bool, bool) {
	if o == nil || IsNil(o.IsApiUser) {
		return nil, false
	}
	return o.IsApiUser, true
}

// HasIsApiUser returns a boolean if a field has been set.
func (o *UserView) HasIsApiUser() bool {
	if o != nil && !IsNil(o.IsApiUser) {
		return true
	}

	return false
}

// SetIsApiUser gets a reference to the given bool and assigns it to the IsApiUser field.
func (o *UserView) SetIsApiUser(v bool) {
	o.IsApiUser = &v
}

// GetIsContentManager returns the IsContentManager field value if set, zero value otherwise.
func (o *UserView) GetIsContentManager() bool {
	if o == nil || IsNil(o.IsContentManager) {
		var ret bool
		return ret
	}
	return *o.IsContentManager
}

// GetIsContentManagerOk returns a tuple with the IsContentManager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIsContentManagerOk() (*bool, bool) {
	if o == nil || IsNil(o.IsContentManager) {
		return nil, false
	}
	return o.IsContentManager, true
}

// HasIsContentManager returns a boolean if a field has been set.
func (o *UserView) HasIsContentManager() bool {
	if o != nil && !IsNil(o.IsContentManager) {
		return true
	}

	return false
}

// SetIsContentManager gets a reference to the given bool and assigns it to the IsContentManager field.
func (o *UserView) SetIsContentManager(v bool) {
	o.IsContentManager = &v
}

// GetIsStandardPlus returns the IsStandardPlus field value if set, zero value otherwise.
func (o *UserView) GetIsStandardPlus() bool {
	if o == nil || IsNil(o.IsStandardPlus) {
		var ret bool
		return ret
	}
	return *o.IsStandardPlus
}

// GetIsStandardPlusOk returns a tuple with the IsStandardPlus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIsStandardPlusOk() (*bool, bool) {
	if o == nil || IsNil(o.IsStandardPlus) {
		return nil, false
	}
	return o.IsStandardPlus, true
}

// HasIsStandardPlus returns a boolean if a field has been set.
func (o *UserView) HasIsStandardPlus() bool {
	if o != nil && !IsNil(o.IsStandardPlus) {
		return true
	}

	return false
}

// SetIsStandardPlus gets a reference to the given bool and assigns it to the IsStandardPlus field.
func (o *UserView) SetIsStandardPlus(v bool) {
	o.IsStandardPlus = &v
}

// GetAlwaysRequireManagerApproval returns the AlwaysRequireManagerApproval field value if set, zero value otherwise.
func (o *UserView) GetAlwaysRequireManagerApproval() bool {
	if o == nil || IsNil(o.AlwaysRequireManagerApproval) {
		var ret bool
		return ret
	}
	return *o.AlwaysRequireManagerApproval
}

// GetAlwaysRequireManagerApprovalOk returns a tuple with the AlwaysRequireManagerApproval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetAlwaysRequireManagerApprovalOk() (*bool, bool) {
	if o == nil || IsNil(o.AlwaysRequireManagerApproval) {
		return nil, false
	}
	return o.AlwaysRequireManagerApproval, true
}

// HasAlwaysRequireManagerApproval returns a boolean if a field has been set.
func (o *UserView) HasAlwaysRequireManagerApproval() bool {
	if o != nil && !IsNil(o.AlwaysRequireManagerApproval) {
		return true
	}

	return false
}

// SetAlwaysRequireManagerApproval gets a reference to the given bool and assigns it to the AlwaysRequireManagerApproval field.
func (o *UserView) SetAlwaysRequireManagerApproval(v bool) {
	o.AlwaysRequireManagerApproval = &v
}

// GetIsPublisher returns the IsPublisher field value if set, zero value otherwise.
func (o *UserView) GetIsPublisher() bool {
	if o == nil || IsNil(o.IsPublisher) {
		var ret bool
		return ret
	}
	return *o.IsPublisher
}

// GetIsPublisherOk returns a tuple with the IsPublisher field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIsPublisherOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublisher) {
		return nil, false
	}
	return o.IsPublisher, true
}

// HasIsPublisher returns a boolean if a field has been set.
func (o *UserView) HasIsPublisher() bool {
	if o != nil && !IsNil(o.IsPublisher) {
		return true
	}

	return false
}

// SetIsPublisher gets a reference to the given bool and assigns it to the IsPublisher field.
func (o *UserView) SetIsPublisher(v bool) {
	o.IsPublisher = &v
}

// GetIsManualWinner returns the IsManualWinner field value if set, zero value otherwise.
func (o *UserView) GetIsManualWinner() bool {
	if o == nil || IsNil(o.IsManualWinner) {
		var ret bool
		return ret
	}
	return *o.IsManualWinner
}

// GetIsManualWinnerOk returns a tuple with the IsManualWinner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIsManualWinnerOk() (*bool, bool) {
	if o == nil || IsNil(o.IsManualWinner) {
		return nil, false
	}
	return o.IsManualWinner, true
}

// HasIsManualWinner returns a boolean if a field has been set.
func (o *UserView) HasIsManualWinner() bool {
	if o != nil && !IsNil(o.IsManualWinner) {
		return true
	}

	return false
}

// SetIsManualWinner gets a reference to the given bool and assigns it to the IsManualWinner field.
func (o *UserView) SetIsManualWinner(v bool) {
	o.IsManualWinner = &v
}

// GetElectronicOrderUser returns the ElectronicOrderUser field value if set, zero value otherwise.
func (o *UserView) GetElectronicOrderUser() bool {
	if o == nil || IsNil(o.ElectronicOrderUser) {
		var ret bool
		return ret
	}
	return *o.ElectronicOrderUser
}

// GetElectronicOrderUserOk returns a tuple with the ElectronicOrderUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetElectronicOrderUserOk() (*bool, bool) {
	if o == nil || IsNil(o.ElectronicOrderUser) {
		return nil, false
	}
	return o.ElectronicOrderUser, true
}

// HasElectronicOrderUser returns a boolean if a field has been set.
func (o *UserView) HasElectronicOrderUser() bool {
	if o != nil && !IsNil(o.ElectronicOrderUser) {
		return true
	}

	return false
}

// SetElectronicOrderUser gets a reference to the given bool and assigns it to the ElectronicOrderUser field.
func (o *UserView) SetElectronicOrderUser(v bool) {
	o.ElectronicOrderUser = &v
}

// GetIdProfileTeams returns the IdProfileTeams field value if set, zero value otherwise.
func (o *UserView) GetIdProfileTeams() string {
	if o == nil || IsNil(o.IdProfileTeams) {
		var ret string
		return ret
	}
	return *o.IdProfileTeams
}

// GetIdProfileTeamsOk returns a tuple with the IdProfileTeams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetIdProfileTeamsOk() (*string, bool) {
	if o == nil || IsNil(o.IdProfileTeams) {
		return nil, false
	}
	return o.IdProfileTeams, true
}

// HasIdProfileTeams returns a boolean if a field has been set.
func (o *UserView) HasIdProfileTeams() bool {
	if o != nil && !IsNil(o.IdProfileTeams) {
		return true
	}

	return false
}

// SetIdProfileTeams gets a reference to the given string and assigns it to the IdProfileTeams field.
func (o *UserView) SetIdProfileTeams(v string) {
	o.IdProfileTeams = &v
}

// GetLocationId returns the LocationId field value if set, zero value otherwise.
func (o *UserView) GetLocationId() string {
	if o == nil || IsNil(o.LocationId) {
		var ret string
		return ret
	}
	return *o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetLocationIdOk() (*string, bool) {
	if o == nil || IsNil(o.LocationId) {
		return nil, false
	}
	return o.LocationId, true
}

// HasLocationId returns a boolean if a field has been set.
func (o *UserView) HasLocationId() bool {
	if o != nil && !IsNil(o.LocationId) {
		return true
	}

	return false
}

// SetLocationId gets a reference to the given string and assigns it to the LocationId field.
func (o *UserView) SetLocationId(v string) {
	o.LocationId = &v
}

// GetManagerUserId returns the ManagerUserId field value if set, zero value otherwise.
func (o *UserView) GetManagerUserId() string {
	if o == nil || IsNil(o.ManagerUserId) {
		var ret string
		return ret
	}
	return *o.ManagerUserId
}

// GetManagerUserIdOk returns a tuple with the ManagerUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetManagerUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.ManagerUserId) {
		return nil, false
	}
	return o.ManagerUserId, true
}

// HasManagerUserId returns a boolean if a field has been set.
func (o *UserView) HasManagerUserId() bool {
	if o != nil && !IsNil(o.ManagerUserId) {
		return true
	}

	return false
}

// SetManagerUserId gets a reference to the given string and assigns it to the ManagerUserId field.
func (o *UserView) SetManagerUserId(v string) {
	o.ManagerUserId = &v
}

// GetApproverUserId returns the ApproverUserId field value if set, zero value otherwise.
func (o *UserView) GetApproverUserId() string {
	if o == nil || IsNil(o.ApproverUserId) {
		var ret string
		return ret
	}
	return *o.ApproverUserId
}

// GetApproverUserIdOk returns a tuple with the ApproverUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetApproverUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.ApproverUserId) {
		return nil, false
	}
	return o.ApproverUserId, true
}

// HasApproverUserId returns a boolean if a field has been set.
func (o *UserView) HasApproverUserId() bool {
	if o != nil && !IsNil(o.ApproverUserId) {
		return true
	}

	return false
}

// SetApproverUserId gets a reference to the given string and assigns it to the ApproverUserId field.
func (o *UserView) SetApproverUserId(v string) {
	o.ApproverUserId = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *UserView) GetUserName() string {
	if o == nil || IsNil(o.UserName) {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetUserNameOk() (*string, bool) {
	if o == nil || IsNil(o.UserName) {
		return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *UserView) HasUserName() bool {
	if o != nil && !IsNil(o.UserName) {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *UserView) SetUserName(v string) {
	o.UserName = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UserView) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UserView) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UserView) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UserView) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UserView) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UserView) SetLastName(v string) {
	o.LastName = &v
}

// GetPresentedName returns the PresentedName field value if set, zero value otherwise.
func (o *UserView) GetPresentedName() string {
	if o == nil || IsNil(o.PresentedName) {
		var ret string
		return ret
	}
	return *o.PresentedName
}

// GetPresentedNameOk returns a tuple with the PresentedName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetPresentedNameOk() (*string, bool) {
	if o == nil || IsNil(o.PresentedName) {
		return nil, false
	}
	return o.PresentedName, true
}

// HasPresentedName returns a boolean if a field has been set.
func (o *UserView) HasPresentedName() bool {
	if o != nil && !IsNil(o.PresentedName) {
		return true
	}

	return false
}

// SetPresentedName gets a reference to the given string and assigns it to the PresentedName field.
func (o *UserView) SetPresentedName(v string) {
	o.PresentedName = &v
}

// GetJobTitle returns the JobTitle field value if set, zero value otherwise.
func (o *UserView) GetJobTitle() string {
	if o == nil || IsNil(o.JobTitle) {
		var ret string
		return ret
	}
	return *o.JobTitle
}

// GetJobTitleOk returns a tuple with the JobTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetJobTitleOk() (*string, bool) {
	if o == nil || IsNil(o.JobTitle) {
		return nil, false
	}
	return o.JobTitle, true
}

// HasJobTitle returns a boolean if a field has been set.
func (o *UserView) HasJobTitle() bool {
	if o != nil && !IsNil(o.JobTitle) {
		return true
	}

	return false
}

// SetJobTitle gets a reference to the given string and assigns it to the JobTitle field.
func (o *UserView) SetJobTitle(v string) {
	o.JobTitle = &v
}

// GetQuotePreface returns the QuotePreface field value if set, zero value otherwise.
func (o *UserView) GetQuotePreface() string {
	if o == nil || IsNil(o.QuotePreface) {
		var ret string
		return ret
	}
	return *o.QuotePreface
}

// GetQuotePrefaceOk returns a tuple with the QuotePreface field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetQuotePrefaceOk() (*string, bool) {
	if o == nil || IsNil(o.QuotePreface) {
		return nil, false
	}
	return o.QuotePreface, true
}

// HasQuotePreface returns a boolean if a field has been set.
func (o *UserView) HasQuotePreface() bool {
	if o != nil && !IsNil(o.QuotePreface) {
		return true
	}

	return false
}

// SetQuotePreface gets a reference to the given string and assigns it to the QuotePreface field.
func (o *UserView) SetQuotePreface(v string) {
	o.QuotePreface = &v
}

// GetUserNotes returns the UserNotes field value if set, zero value otherwise.
func (o *UserView) GetUserNotes() string {
	if o == nil || IsNil(o.UserNotes) {
		var ret string
		return ret
	}
	return *o.UserNotes
}

// GetUserNotesOk returns a tuple with the UserNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetUserNotesOk() (*string, bool) {
	if o == nil || IsNil(o.UserNotes) {
		return nil, false
	}
	return o.UserNotes, true
}

// HasUserNotes returns a boolean if a field has been set.
func (o *UserView) HasUserNotes() bool {
	if o != nil && !IsNil(o.UserNotes) {
		return true
	}

	return false
}

// SetUserNotes gets a reference to the given string and assigns it to the UserNotes field.
func (o *UserView) SetUserNotes(v string) {
	o.UserNotes = &v
}

// GetBaseCurrency returns the BaseCurrency field value if set, zero value otherwise.
func (o *UserView) GetBaseCurrency() string {
	if o == nil || IsNil(o.BaseCurrency) {
		var ret string
		return ret
	}
	return *o.BaseCurrency
}

// GetBaseCurrencyOk returns a tuple with the BaseCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetBaseCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.BaseCurrency) {
		return nil, false
	}
	return o.BaseCurrency, true
}

// HasBaseCurrency returns a boolean if a field has been set.
func (o *UserView) HasBaseCurrency() bool {
	if o != nil && !IsNil(o.BaseCurrency) {
		return true
	}

	return false
}

// SetBaseCurrency gets a reference to the given string and assigns it to the BaseCurrency field.
func (o *UserView) SetBaseCurrency(v string) {
	o.BaseCurrency = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *UserView) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *UserView) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *UserView) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetMobilePhoneNumber returns the MobilePhoneNumber field value if set, zero value otherwise.
func (o *UserView) GetMobilePhoneNumber() string {
	if o == nil || IsNil(o.MobilePhoneNumber) {
		var ret string
		return ret
	}
	return *o.MobilePhoneNumber
}

// GetMobilePhoneNumberOk returns a tuple with the MobilePhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetMobilePhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.MobilePhoneNumber) {
		return nil, false
	}
	return o.MobilePhoneNumber, true
}

// HasMobilePhoneNumber returns a boolean if a field has been set.
func (o *UserView) HasMobilePhoneNumber() bool {
	if o != nil && !IsNil(o.MobilePhoneNumber) {
		return true
	}

	return false
}

// SetMobilePhoneNumber gets a reference to the given string and assigns it to the MobilePhoneNumber field.
func (o *UserView) SetMobilePhoneNumber(v string) {
	o.MobilePhoneNumber = &v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise.
func (o *UserView) GetEmailAddress() string {
	if o == nil || IsNil(o.EmailAddress) {
		var ret string
		return ret
	}
	return *o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetEmailAddressOk() (*string, bool) {
	if o == nil || IsNil(o.EmailAddress) {
		return nil, false
	}
	return o.EmailAddress, true
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *UserView) HasEmailAddress() bool {
	if o != nil && !IsNil(o.EmailAddress) {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given string and assigns it to the EmailAddress field.
func (o *UserView) SetEmailAddress(v string) {
	o.EmailAddress = &v
}

// GetMessengerId returns the MessengerId field value if set, zero value otherwise.
func (o *UserView) GetMessengerId() string {
	if o == nil || IsNil(o.MessengerId) {
		var ret string
		return ret
	}
	return *o.MessengerId
}

// GetMessengerIdOk returns a tuple with the MessengerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetMessengerIdOk() (*string, bool) {
	if o == nil || IsNil(o.MessengerId) {
		return nil, false
	}
	return o.MessengerId, true
}

// HasMessengerId returns a boolean if a field has been set.
func (o *UserView) HasMessengerId() bool {
	if o != nil && !IsNil(o.MessengerId) {
		return true
	}

	return false
}

// SetMessengerId gets a reference to the given string and assigns it to the MessengerId field.
func (o *UserView) SetMessengerId(v string) {
	o.MessengerId = &v
}

// GetInvoiceRepId returns the InvoiceRepId field value if set, zero value otherwise.
func (o *UserView) GetInvoiceRepId() string {
	if o == nil || IsNil(o.InvoiceRepId) {
		var ret string
		return ret
	}
	return *o.InvoiceRepId
}

// GetInvoiceRepIdOk returns a tuple with the InvoiceRepId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetInvoiceRepIdOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceRepId) {
		return nil, false
	}
	return o.InvoiceRepId, true
}

// HasInvoiceRepId returns a boolean if a field has been set.
func (o *UserView) HasInvoiceRepId() bool {
	if o != nil && !IsNil(o.InvoiceRepId) {
		return true
	}

	return false
}

// SetInvoiceRepId gets a reference to the given string and assigns it to the InvoiceRepId field.
func (o *UserView) SetInvoiceRepId(v string) {
	o.InvoiceRepId = &v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *UserView) GetTimeZone() string {
	if o == nil || IsNil(o.TimeZone) {
		var ret string
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetTimeZoneOk() (*string, bool) {
	if o == nil || IsNil(o.TimeZone) {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *UserView) HasTimeZone() bool {
	if o != nil && !IsNil(o.TimeZone) {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given string and assigns it to the TimeZone field.
func (o *UserView) SetTimeZone(v string) {
	o.TimeZone = &v
}

// GetOrderPorterEmailAddresses returns the OrderPorterEmailAddresses field value if set, zero value otherwise.
func (o *UserView) GetOrderPorterEmailAddresses() string {
	if o == nil || IsNil(o.OrderPorterEmailAddresses) {
		var ret string
		return ret
	}
	return *o.OrderPorterEmailAddresses
}

// GetOrderPorterEmailAddressesOk returns a tuple with the OrderPorterEmailAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetOrderPorterEmailAddressesOk() (*string, bool) {
	if o == nil || IsNil(o.OrderPorterEmailAddresses) {
		return nil, false
	}
	return o.OrderPorterEmailAddresses, true
}

// HasOrderPorterEmailAddresses returns a boolean if a field has been set.
func (o *UserView) HasOrderPorterEmailAddresses() bool {
	if o != nil && !IsNil(o.OrderPorterEmailAddresses) {
		return true
	}

	return false
}

// SetOrderPorterEmailAddresses gets a reference to the given string and assigns it to the OrderPorterEmailAddresses field.
func (o *UserView) SetOrderPorterEmailAddresses(v string) {
	o.OrderPorterEmailAddresses = &v
}

// GetOnBehalfUser returns the OnBehalfUser field value if set, zero value otherwise.
func (o *UserView) GetOnBehalfUser() string {
	if o == nil || IsNil(o.OnBehalfUser) {
		var ret string
		return ret
	}
	return *o.OnBehalfUser
}

// GetOnBehalfUserOk returns a tuple with the OnBehalfUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetOnBehalfUserOk() (*string, bool) {
	if o == nil || IsNil(o.OnBehalfUser) {
		return nil, false
	}
	return o.OnBehalfUser, true
}

// HasOnBehalfUser returns a boolean if a field has been set.
func (o *UserView) HasOnBehalfUser() bool {
	if o != nil && !IsNil(o.OnBehalfUser) {
		return true
	}

	return false
}

// SetOnBehalfUser gets a reference to the given string and assigns it to the OnBehalfUser field.
func (o *UserView) SetOnBehalfUser(v string) {
	o.OnBehalfUser = &v
}

// GetDefaultSearchQuoteStatus returns the DefaultSearchQuoteStatus field value if set, zero value otherwise.
func (o *UserView) GetDefaultSearchQuoteStatus() string {
	if o == nil || IsNil(o.DefaultSearchQuoteStatus) {
		var ret string
		return ret
	}
	return *o.DefaultSearchQuoteStatus
}

// GetDefaultSearchQuoteStatusOk returns a tuple with the DefaultSearchQuoteStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetDefaultSearchQuoteStatusOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultSearchQuoteStatus) {
		return nil, false
	}
	return o.DefaultSearchQuoteStatus, true
}

// HasDefaultSearchQuoteStatus returns a boolean if a field has been set.
func (o *UserView) HasDefaultSearchQuoteStatus() bool {
	if o != nil && !IsNil(o.DefaultSearchQuoteStatus) {
		return true
	}

	return false
}

// SetDefaultSearchQuoteStatus gets a reference to the given string and assigns it to the DefaultSearchQuoteStatus field.
func (o *UserView) SetDefaultSearchQuoteStatus(v string) {
	o.DefaultSearchQuoteStatus = &v
}

// GetBccEmailAddresses returns the BccEmailAddresses field value if set, zero value otherwise.
func (o *UserView) GetBccEmailAddresses() string {
	if o == nil || IsNil(o.BccEmailAddresses) {
		var ret string
		return ret
	}
	return *o.BccEmailAddresses
}

// GetBccEmailAddressesOk returns a tuple with the BccEmailAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetBccEmailAddressesOk() (*string, bool) {
	if o == nil || IsNil(o.BccEmailAddresses) {
		return nil, false
	}
	return o.BccEmailAddresses, true
}

// HasBccEmailAddresses returns a boolean if a field has been set.
func (o *UserView) HasBccEmailAddresses() bool {
	if o != nil && !IsNil(o.BccEmailAddresses) {
		return true
	}

	return false
}

// SetBccEmailAddresses gets a reference to the given string and assigns it to the BccEmailAddresses field.
func (o *UserView) SetBccEmailAddresses(v string) {
	o.BccEmailAddresses = &v
}

// GetOauthSubscriberId returns the OauthSubscriberId field value if set, zero value otherwise.
func (o *UserView) GetOauthSubscriberId() string {
	if o == nil || IsNil(o.OauthSubscriberId) {
		var ret string
		return ret
	}
	return *o.OauthSubscriberId
}

// GetOauthSubscriberIdOk returns a tuple with the OauthSubscriberId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserView) GetOauthSubscriberIdOk() (*string, bool) {
	if o == nil || IsNil(o.OauthSubscriberId) {
		return nil, false
	}
	return o.OauthSubscriberId, true
}

// HasOauthSubscriberId returns a boolean if a field has been set.
func (o *UserView) HasOauthSubscriberId() bool {
	if o != nil && !IsNil(o.OauthSubscriberId) {
		return true
	}

	return false
}

// SetOauthSubscriberId gets a reference to the given string and assigns it to the OauthSubscriberId field.
func (o *UserView) SetOauthSubscriberId(v string) {
	o.OauthSubscriberId = &v
}

func (o UserView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IsInactiveUser) {
		toSerialize["isInactiveUser"] = o.IsInactiveUser
	}
	if !IsNil(o.IsReadOnlyUser) {
		toSerialize["isReadOnlyUser"] = o.IsReadOnlyUser
	}
	if !IsNil(o.FailedLoginCount) {
		toSerialize["failedLoginCount"] = o.FailedLoginCount
	}
	if !IsNil(o.IsApprover) {
		toSerialize["isApprover"] = o.IsApprover
	}
	if !IsNil(o.IsPriceChanger) {
		toSerialize["isPriceChanger"] = o.IsPriceChanger
	}
	if !IsNil(o.CanAccessAllQuotes) {
		toSerialize["canAccessAllQuotes"] = o.CanAccessAllQuotes
	}
	if !IsNil(o.IsAdministrator) {
		toSerialize["isAdministrator"] = o.IsAdministrator
	}
	if !IsNil(o.IsDeveloper) {
		toSerialize["isDeveloper"] = o.IsDeveloper
	}
	if !IsNil(o.IsApiUser) {
		toSerialize["isApiUser"] = o.IsApiUser
	}
	if !IsNil(o.IsContentManager) {
		toSerialize["isContentManager"] = o.IsContentManager
	}
	if !IsNil(o.IsStandardPlus) {
		toSerialize["isStandardPlus"] = o.IsStandardPlus
	}
	if !IsNil(o.AlwaysRequireManagerApproval) {
		toSerialize["alwaysRequireManagerApproval"] = o.AlwaysRequireManagerApproval
	}
	if !IsNil(o.IsPublisher) {
		toSerialize["isPublisher"] = o.IsPublisher
	}
	if !IsNil(o.IsManualWinner) {
		toSerialize["isManualWinner"] = o.IsManualWinner
	}
	if !IsNil(o.ElectronicOrderUser) {
		toSerialize["electronicOrderUser"] = o.ElectronicOrderUser
	}
	if !IsNil(o.IdProfileTeams) {
		toSerialize["idProfileTeams"] = o.IdProfileTeams
	}
	if !IsNil(o.LocationId) {
		toSerialize["locationId"] = o.LocationId
	}
	if !IsNil(o.ManagerUserId) {
		toSerialize["managerUserId"] = o.ManagerUserId
	}
	if !IsNil(o.ApproverUserId) {
		toSerialize["approverUserId"] = o.ApproverUserId
	}
	if !IsNil(o.UserName) {
		toSerialize["userName"] = o.UserName
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.PresentedName) {
		toSerialize["presentedName"] = o.PresentedName
	}
	if !IsNil(o.JobTitle) {
		toSerialize["jobTitle"] = o.JobTitle
	}
	if !IsNil(o.QuotePreface) {
		toSerialize["quotePreface"] = o.QuotePreface
	}
	if !IsNil(o.UserNotes) {
		toSerialize["userNotes"] = o.UserNotes
	}
	if !IsNil(o.BaseCurrency) {
		toSerialize["baseCurrency"] = o.BaseCurrency
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	if !IsNil(o.MobilePhoneNumber) {
		toSerialize["mobilePhoneNumber"] = o.MobilePhoneNumber
	}
	if !IsNil(o.EmailAddress) {
		toSerialize["emailAddress"] = o.EmailAddress
	}
	if !IsNil(o.MessengerId) {
		toSerialize["messengerId"] = o.MessengerId
	}
	if !IsNil(o.InvoiceRepId) {
		toSerialize["invoiceRepId"] = o.InvoiceRepId
	}
	if !IsNil(o.TimeZone) {
		toSerialize["timeZone"] = o.TimeZone
	}
	if !IsNil(o.OrderPorterEmailAddresses) {
		toSerialize["orderPorterEmailAddresses"] = o.OrderPorterEmailAddresses
	}
	if !IsNil(o.OnBehalfUser) {
		toSerialize["onBehalfUser"] = o.OnBehalfUser
	}
	if !IsNil(o.DefaultSearchQuoteStatus) {
		toSerialize["defaultSearchQuoteStatus"] = o.DefaultSearchQuoteStatus
	}
	if !IsNil(o.BccEmailAddresses) {
		toSerialize["bccEmailAddresses"] = o.BccEmailAddresses
	}
	if !IsNil(o.OauthSubscriberId) {
		toSerialize["oauthSubscriberId"] = o.OauthSubscriberId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserView) UnmarshalJSON(data []byte) (err error) {
	varUserView := _UserView{}

	err = json.Unmarshal(data, &varUserView)

	if err != nil {
		return err
	}

	*o = UserView(varUserView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "isInactiveUser")
		delete(additionalProperties, "isReadOnlyUser")
		delete(additionalProperties, "failedLoginCount")
		delete(additionalProperties, "isApprover")
		delete(additionalProperties, "isPriceChanger")
		delete(additionalProperties, "canAccessAllQuotes")
		delete(additionalProperties, "isAdministrator")
		delete(additionalProperties, "isDeveloper")
		delete(additionalProperties, "isApiUser")
		delete(additionalProperties, "isContentManager")
		delete(additionalProperties, "isStandardPlus")
		delete(additionalProperties, "alwaysRequireManagerApproval")
		delete(additionalProperties, "isPublisher")
		delete(additionalProperties, "isManualWinner")
		delete(additionalProperties, "electronicOrderUser")
		delete(additionalProperties, "idProfileTeams")
		delete(additionalProperties, "locationId")
		delete(additionalProperties, "managerUserId")
		delete(additionalProperties, "approverUserId")
		delete(additionalProperties, "userName")
		delete(additionalProperties, "firstName")
		delete(additionalProperties, "lastName")
		delete(additionalProperties, "presentedName")
		delete(additionalProperties, "jobTitle")
		delete(additionalProperties, "quotePreface")
		delete(additionalProperties, "userNotes")
		delete(additionalProperties, "baseCurrency")
		delete(additionalProperties, "phoneNumber")
		delete(additionalProperties, "mobilePhoneNumber")
		delete(additionalProperties, "emailAddress")
		delete(additionalProperties, "messengerId")
		delete(additionalProperties, "invoiceRepId")
		delete(additionalProperties, "timeZone")
		delete(additionalProperties, "orderPorterEmailAddresses")
		delete(additionalProperties, "onBehalfUser")
		delete(additionalProperties, "defaultSearchQuoteStatus")
		delete(additionalProperties, "bccEmailAddresses")
		delete(additionalProperties, "oauthSubscriberId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserView struct {
	value *UserView
	isSet bool
}

func (v NullableUserView) Get() *UserView {
	return v.value
}

func (v *NullableUserView) Set(val *UserView) {
	v.value = val
	v.isSet = true
}

func (v NullableUserView) IsSet() bool {
	return v.isSet
}

func (v *NullableUserView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserView(val *UserView) *NullableUserView {
	return &NullableUserView{value: val, isSet: true}
}

func (v NullableUserView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
