/*
ConnectWiseSellService

Version 1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connectwisesellapi

import (
	"encoding/json"
)

// checks if the ViewQueryModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewQueryModel{}

// ViewQueryModel struct for ViewQueryModel
type ViewQueryModel struct {
	// Comma separated list of fields to return.
	IncludeFields *string `json:"includeFields,omitempty"`
	// Conditional retrieve statements.
	Conditions *string `json:"conditions,omitempty"`
	// Page of results to get. 1-index based.
	Page *int32 `json:"page,omitempty"`
	// Page size of results to get. Max size 1000, default 50.
	PageSize             *int32 `json:"pageSize,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ViewQueryModel ViewQueryModel

// NewViewQueryModel instantiates a new ViewQueryModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewQueryModel() *ViewQueryModel {
	this := ViewQueryModel{}
	return &this
}

// NewViewQueryModelWithDefaults instantiates a new ViewQueryModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewQueryModelWithDefaults() *ViewQueryModel {
	this := ViewQueryModel{}
	return &this
}

// GetIncludeFields returns the IncludeFields field value if set, zero value otherwise.
func (o *ViewQueryModel) GetIncludeFields() string {
	if o == nil || IsNil(o.IncludeFields) {
		var ret string
		return ret
	}
	return *o.IncludeFields
}

// GetIncludeFieldsOk returns a tuple with the IncludeFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewQueryModel) GetIncludeFieldsOk() (*string, bool) {
	if o == nil || IsNil(o.IncludeFields) {
		return nil, false
	}
	return o.IncludeFields, true
}

// HasIncludeFields returns a boolean if a field has been set.
func (o *ViewQueryModel) HasIncludeFields() bool {
	if o != nil && !IsNil(o.IncludeFields) {
		return true
	}

	return false
}

// SetIncludeFields gets a reference to the given string and assigns it to the IncludeFields field.
func (o *ViewQueryModel) SetIncludeFields(v string) {
	o.IncludeFields = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *ViewQueryModel) GetConditions() string {
	if o == nil || IsNil(o.Conditions) {
		var ret string
		return ret
	}
	return *o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewQueryModel) GetConditionsOk() (*string, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *ViewQueryModel) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given string and assigns it to the Conditions field.
func (o *ViewQueryModel) SetConditions(v string) {
	o.Conditions = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ViewQueryModel) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewQueryModel) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ViewQueryModel) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *ViewQueryModel) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *ViewQueryModel) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewQueryModel) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *ViewQueryModel) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *ViewQueryModel) SetPageSize(v int32) {
	o.PageSize = &v
}

func (o ViewQueryModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewQueryModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IncludeFields) {
		toSerialize["includeFields"] = o.IncludeFields
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ViewQueryModel) UnmarshalJSON(data []byte) (err error) {
	varViewQueryModel := _ViewQueryModel{}

	err = json.Unmarshal(data, &varViewQueryModel)

	if err != nil {
		return err
	}

	*o = ViewQueryModel(varViewQueryModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "includeFields")
		delete(additionalProperties, "conditions")
		delete(additionalProperties, "page")
		delete(additionalProperties, "pageSize")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableViewQueryModel struct {
	value *ViewQueryModel
	isSet bool
}

func (v NullableViewQueryModel) Get() *ViewQueryModel {
	return v.value
}

func (v *NullableViewQueryModel) Set(val *ViewQueryModel) {
	v.value = val
	v.isSet = true
}

func (v NullableViewQueryModel) IsSet() bool {
	return v.isSet
}

func (v *NullableViewQueryModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewQueryModel(val *ViewQueryModel) *NullableViewQueryModel {
	return &NullableViewQueryModel{value: val, isSet: true}
}

func (v NullableViewQueryModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewQueryModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
